import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {paymentRequiredHeader} from "@/lib/challenge";
import {rateLimit,safeError} from "@/lib/http";
import {isCid} from "@/packages/filecoin/src/cid";
import {executeRetrieval,offerRetrieval} from "@/packages/filecoin/src/gateway";
import {getObject} from "@/packages/filecoin/src/store";
const Agent=z.string().uuid();export const dynamic="force-dynamic";export const maxDuration=120;
export async function HEAD(_req:NextRequest,{params}:{params:Promise<{cid:string}>}){const {cid}=await params;if(!isCid(cid))return new Response(null,{status:400});const object=await getObject(cid);return new Response(null,{status:object?200:404,headers:object?{"content-length":String(object.sizeBytes),"x-storage-status":object.status,"x-proof-status":object.proofStatus||"unknown"}:{}})}
export async function GET(req:NextRequest,{params}:{params:Promise<{cid:string}>}){const limited=await rateLimit(req,30);if(limited)return limited;try{const {cid}=await params;if(!isCid(cid))throw new Error("invalid_cid");const rawAgent=req.headers.get("x-agent-id"),agentId=rawAgent?Agent.parse(rawAgent):undefined,quoteId=req.headers.get("x-storage-quote-id"),paymentId=req.headers.get("x-payment-id"),requestId=req.headers.get("idempotency-key"),resource=`${process.env.APP_URL||new URL(req.url).origin}/api/storage/v1/cids/${cid}`;if(!quoteId&&!paymentId){const offer=await offerRetrieval(cid,resource,agentId);return NextResponse.json({error:"payment_required",quote:offer.quote,estimate:offer.estimate,object:{cid,size:offer.object.sizeBytes,status:offer.object.status},paymentRequirements:offer.challenge},{status:402,headers:{"payment-required":paymentRequiredHeader(offer.challenge),"cache-control":"no-store"}})}if(!quoteId||!paymentId||!requestId)throw new Error("payment_headers_incomplete");const result=await executeRetrieval({cid,quoteId,paymentId,requestId,agentId});return new Response(result.bytes.slice().buffer as ArrayBuffer,{headers:{"content-type":result.object.contentType||"application/octet-stream","content-length":String(result.bytes.byteLength),"etag":`"${cid}"`,"x-content-cid":cid,"cache-control":"private, no-store"}})}catch(e){const message=e instanceof Error?e.message:"invalid_request",status=message.includes("not_found")?404:message.includes("payment")||message.includes("budget")?402:400;return safeError(message,status)}}
