import {getPostgres} from "../../../db/postgres.ts";
import type {ServiceBudget,ServiceUsage} from "../../x402-core/src/index.ts";
import type {ServiceQuote} from "./domain.ts";
const quotes=new Map<string,ServiceQuote>(),requests=new Map<string,{quoteId:string;status:"processing"|"succeeded"|"failed";response?:unknown;error?:string}>(),usage:Array<{agentId?:string;service:string;amount:string;createdAt:string}>=[];
const budgets=new Map<string,ServiceBudget>();
export async function createQuote(quote:ServiceQuote){if(!process.env.DATABASE_URL){quotes.set(quote.id,quote);return}const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into service_quotes(id,service,agent_id,request_hash,amount,asset,network,provider_id,expires_at,status) values(${quote.id},${quote.service},${quote.agentId||null},${quote.requestHash},${quote.amount},${quote.asset},${quote.network},${quote.providerId||null},${quote.expiresAt},${quote.status})`}
export async function getQuote(id:string):Promise<ServiceQuote|null>{if(!process.env.DATABASE_URL)return quotes.get(id)||null;const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`select * from service_quotes where id=${id}`;if(!rows[0])return null;const r=rows[0];return {id:r.id,service:r.service,agentId:r.agent_id||undefined,requestHash:r.request_hash,amount:String(r.amount),asset:r.asset,network:r.network,providerId:r.provider_id||undefined,expiresAt:new Date(r.expires_at).toISOString(),status:r.status,paymentId:r.payment_id||undefined}}
export async function authorizeQuote(id:string,paymentId:string){if(!process.env.DATABASE_URL){const q=quotes.get(id);if(!q||q.status!=="offered")return q?.paymentId===paymentId;for(const x of quotes.values())if(x.paymentId===paymentId)return false;quotes.set(id,{...q,status:"authorized",paymentId});return true}const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`update service_quotes set status='authorized',payment_id=${paymentId},updated_at=now() where id=${id} and status='offered' and expires_at>now() returning id`;if(rows.length)return true;const q=await getQuote(id);return (q?.status==="authorized"||q?.status==="consumed")&&q.paymentId===paymentId}
export async function claimRequest(id:string,quoteId:string,agentId?:string,kind:"inference"|"deployment"|"storage"|"retrieval"|"search"="inference"){if(!process.env.DATABASE_URL){const old=requests.get(id);if(old?.status==="succeeded")return {claimed:false,response:old.response};if(old?.quoteId!==quoteId&&old)throw new Error("idempotency_conflict");requests.set(id,{quoteId,status:"processing"});return {claimed:true}}const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`insert into akash_requests(id,quote_id,agent_id,kind,status) values(${id},${quoteId},${agentId||null},${kind},'processing') on conflict(id) do update set status='processing',error=null,updated_at=now() where akash_requests.quote_id=${quoteId} and akash_requests.status='failed' returning id`;if(rows.length)return {claimed:true};const old=await sql`select quote_id,status,response from akash_requests where id=${id}`;if(old[0]?.quote_id!==quoteId)throw new Error("idempotency_conflict");return {claimed:false,response:old[0]?.response,status:old[0]?.status}}
export async function completeRequest(id:string,quote:ServiceQuote,providerId:string,input:number,output:number,billed:string,response:unknown){if(!process.env.DATABASE_URL){requests.set(id,{quoteId:quote.id,status:"succeeded",response});quotes.set(quote.id,{...quote,status:"consumed"});usage.push({agentId:quote.agentId,service:quote.service,amount:billed,createdAt:new Date().toISOString()});return}const sql=getPostgres();await sql.begin(async tx=>{await tx`update akash_requests set status='succeeded',response=${JSON.stringify(response)}::jsonb,updated_at=now() where id=${id} and status='processing'`;await tx`insert into service_usage(id,service,agent_id,quote_id,request_id,provider_id,input_units,output_units,billed_amount) values(${crypto.randomUUID()},${quote.service},${quote.agentId||null},${quote.id},${id},${providerId},${input},${output},${billed})`;await tx`update service_quotes set status='consumed',updated_at=now() where id=${quote.id} and status='authorized'`})}
export async function failRequest(id:string,error:string){if(!process.env.DATABASE_URL){const old=requests.get(id);if(old)requests.set(id,{...old,status:"failed",error});return}const sql=getPostgres(process.env.DATABASE_URL);await sql`update akash_requests set status='failed',error=${error.slice(0,500)},updated_at=now() where id=${id}`}
export async function getServiceBudget(agentId:string,service:string):Promise<ServiceBudget|null>{if(!process.env.DATABASE_URL)return budgets.get(`${agentId}:${service}`)||null;const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`select * from service_budgets where agent_id=${agentId} and service=${service} and enabled=true`;if(!rows[0])return null;const r=rows[0];return {agentId,service,perRequest:String(r.per_request),daily:String(r.daily_budget),monthly:String(r.monthly_budget)}}
export async function upsertServiceBudget(budget:ServiceBudget,enabled=true){if(!process.env.DATABASE_URL){if(enabled)budgets.set(`${budget.agentId}:${budget.service}`,budget);else budgets.delete(`${budget.agentId}:${budget.service}`);return}const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into service_budgets(agent_id,service,per_request,daily_budget,monthly_budget,enabled) values(${budget.agentId},${budget.service},${budget.perRequest},${budget.daily},${budget.monthly},${enabled}) on conflict(agent_id,service) do update set per_request=excluded.per_request,daily_budget=excluded.daily_budget,monthly_budget=excluded.monthly_budget,enabled=excluded.enabled`}
export async function getServiceUsage(agentId:string,service:string):Promise<ServiceUsage>{if(!process.env.DATABASE_URL){const now=new Date(),items=usage.filter(x=>x.agentId===agentId&&x.service===service),daily=items.filter(x=>new Date(x.createdAt).toDateString()===now.toDateString()).reduce((n,x)=>n+BigInt(x.amount),0n),monthly=items.filter(x=>{const d=new Date(x.createdAt);return d.getUTCFullYear()===now.getUTCFullYear()&&d.getUTCMonth()===now.getUTCMonth()}).reduce((n,x)=>n+BigInt(x.amount),0n);return {daily:String(daily),monthly:String(monthly)}}const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`select coalesce(sum(billed_amount) filter(where created_at>=date_trunc('day',now())),0)::text daily,coalesce(sum(billed_amount) filter(where created_at>=date_trunc('month',now())),0)::text monthly from service_usage where agent_id=${agentId} and service=${service}`;return {daily:String(rows[0].daily),monthly:String(rows[0].monthly)}}
export async function saveDeployment(input:{id:string;agentId?:string;quoteId:string;externalId?:string;providerId?:string;image:string;cpuMillis:number;memoryMiB:number;gpuModel?:string;gpuUnits:number;maxHours:number;status:string;closeAfter:string;error?:string}){if(!process.env.DATABASE_URL)return;const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into akash_deployments(id,agent_id,quote_id,external_id,provider_id,image,cpu_millis,memory_mib,gpu_model,gpu_units,max_hours,status,close_after,error) values(${input.id},${input.agentId||null},${input.quoteId},${input.externalId||null},${input.providerId||null},${input.image},${input.cpuMillis},${input.memoryMiB},${input.gpuModel||null},${input.gpuUnits},${input.maxHours},${input.status},${input.closeAfter},${input.error||null})`}
