"use client";
import { useState } from "react";
import { connectAdena,signG402Payment,type AdenaAccount } from "@/lib/adena";
import type { PaymentRequirements } from "@/lib/domain";

export default function WalletClient(){
  const [account,setAccount]=useState<AdenaAccount|null>(null),[error,setError]=useState(""),[signed,setSigned]=useState("");
  async function connect(){setError("");try{setAccount(await connectAdena())}catch(e){setError(e instanceof Error?e.message:"wallet_error")}}
  async function signSample(){if(!account)return;setError("");try{const response=await fetch("/api/demo/paid-data",{cache:"no-store"}),body=await response.json() as {paymentRequirements:PaymentRequirements};if(response.status!==402||!body.paymentRequirements)throw new Error("challenge_unavailable");const paymentId=`pay_${crypto.randomUUID().replaceAll("-","")}`,signedTx=await signG402Payment(account,body.paymentRequirements,paymentId);setSigned(JSON.stringify({paymentPayload:{x402Version:2,scheme:"exact",network:body.paymentRequirements.network,payload:{signedTx,payer:account.address,paymentId,createdAt:Math.floor(Date.now()/1000)}},paymentRequirements:body.paymentRequirements},null,2))}catch(e){setError(e instanceof Error?e.message:"signing_failed")}}
  return <><div className="grid twoCol"><div className="card feature"><div className="eyebrow">NON-CUSTODIAL</div><h3>Adena Wallet</h3><p>키는 브라우저 확장 프로그램을 떠나지 않습니다. g402는 승인된 서명 문서만 받습니다.</p><button className="button" onClick={connect}>{account?"Connected":"Connect Adena"}</button>{account&&<button className="button secondary spaced" onClick={signSample}>Sign sample payment</button>}{error&&<p className="failed">{error}</p>}</div><div className="card feature"><h3>Current account</h3>{account?<><div className="statusLine"><span>Address</span><b className="mono">{account.address.slice(0,10)}…{account.address.slice(-6)}</b></div><div className="statusLine"><span>Network</span><b>{account.chainId}</b></div><div className="statusLine"><span>Sequence</span><b>{account.sequence}</b></div><div className="statusLine"><span>Balance</span><b>{account.coins}</b></div></>:<p>Connect Adena to load account state.</p>}</div></div>{signed&&<div className="card feature" style={{marginTop:14}}><h3>Signed facilitator request</h3><p>Submit this envelope to <span className="mono">/api/v1/verify</span>, then <span className="mono">/api/v1/settle</span>.</p><pre className="code">{signed}</pre></div>}</>
}
