"use client";
import { useState } from "react";
import { connectAdena,signG402Payment,type AdenaAccount } from "@/lib/adena";
import type { PaymentRequirements } from "@/lib/domain";

export default function WalletClient(){
  const [account,setAccount]=useState<AdenaAccount|null>(null),[error,setError]=useState(""),[signed,setSigned]=useState(""),[phase,setPhase]=useState("idle"),[receipt,setReceipt]=useState<{paymentId:string;transaction?:string;data?:unknown}|null>(null);
  async function connect(){setError("");try{setAccount(await connectAdena())}catch(e){setError(e instanceof Error?e.message:"wallet_error")}}
  async function runPayment(){if(!account)return;setError("");setReceipt(null);try{setPhase("challenge");const response=await fetch(`/api/demo/paid-data?payTo=${encodeURIComponent(account.address)}`,{cache:"no-store"}),body=await response.json() as {paymentRequirements:PaymentRequirements;error?:string};if(response.status!==402||!body.paymentRequirements)throw new Error(body.error||"challenge_unavailable");const paymentId=`pay_${crypto.randomUUID().replaceAll("-","")}`;setPhase("signing");const signedTx=await signG402Payment(account,body.paymentRequirements,paymentId),request={paymentPayload:{x402Version:2 as const,scheme:"exact" as const,network:body.paymentRequirements.network,payload:{signedTx,payer:account.address,paymentId,createdAt:Math.floor(Date.now()/1000)}},paymentRequirements:body.paymentRequirements};setSigned(JSON.stringify(request,null,2));setPhase("verifying");const verified=await fetch("/api/v1/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(request)}),verification=await verified.json() as {isValid?:boolean;invalidReason?:string;error?:string};if(!verified.ok||!verification.isValid)throw new Error(verification.invalidReason||verification.error||"verification_failed");setPhase("settling");const settled=await fetch("/api/v1/settle",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(request)}),settlement=await settled.json() as {success?:boolean;pending?:boolean;transaction?:string;errorReason?:string;error?:string};if(!settled.ok&&!settlement.pending)throw new Error(settlement.errorReason||settlement.error||"settlement_failed");if(!settlement.success){setReceipt({paymentId,transaction:settlement.transaction});setPhase("pending");return}setPhase("unlocking");const paid=await fetch("/api/demo/paid-data",{headers:{"x-payment-id":paymentId},cache:"no-store"}),data=await paid.json();if(!paid.ok)throw new Error((data as {error?:string}).error||"paid_resource_failed");setReceipt({paymentId,transaction:settlement.transaction,data});setPhase("complete")}catch(e){setPhase("failed");setError(e instanceof Error?e.message:"payment_failed")}}
  const busy=!['idle','complete','failed','pending'].includes(phase);return <><div className="grid twoCol"><div className="card feature"><div className="eyebrow">LIVE PEARL FLOW</div><h3>Adena → Facilitator → Gno</h3><p>발급된 challenge를 Adena에서 서명하고, 서버가 서명·nonce·수취인·금액을 검증한 뒤 Pearl 테스트넷에 브로드캐스트합니다.</p><button className="button" onClick={connect}>{account?"Wallet connected":"Connect Adena"}</button>{account&&<button className="button secondary spaced" onClick={runPayment} disabled={busy}>{busy?`Running: ${phase}`:"Run paid API test"}</button>}{error&&<p className="failed">{error}</p>}{phase==="pending"&&<p className="pending">트랜잭션 결과 확인 대기 중입니다. Scan에서 동기화하세요.</p>}</div><div className="card feature"><h3>Current account</h3>{account?<><div className="statusLine"><span>Address</span><b className="mono">{account.address.slice(0,10)}…{account.address.slice(-6)}</b></div><div className="statusLine"><span>Network</span><b>{account.chainId}</b></div><div className="statusLine"><span>Account</span><b>{account.accountNumber}</b></div><div className="statusLine"><span>Sequence</span><b>{account.sequence}</b></div><div className="statusLine"><span>Balance</span><b>{account.coins}</b></div></>:<p>Connect Adena to load account state.</p>}</div></div>{receipt&&<div className="card feature successCard"><div className="eyebrow">{phase==="complete"?"PAYMENT COMPLETE":"BROADCAST PENDING"}</div><h3>{receipt.paymentId}</h3><div className="statusLine"><span>Transaction</span><b className="mono">{receipt.transaction||"pending"}</b></div>{receipt.data!==undefined&&<pre className="code">{JSON.stringify(receipt.data,null,2)}</pre>}</div>}{signed&&<details className="card feature requestEnvelope"><summary>Signed facilitator request</summary><pre className="code">{signed}</pre></details>}</>
}
