import test from "node:test";
import assert from "node:assert/strict";
import {savePayment} from "../lib/store.ts";
import {executeRetrieval,executeSearch,executeUpload,offerRetrieval,offerSearch,offerUpload} from "../packages/filecoin/src/gateway.ts";
const merchant=`g1${"p".repeat(38)}`;
process.env.G402_MERCHANT_ADDRESS=merchant;
process.env.GNO_NETWORK_ID="gno:pearl-1";
process.env.GNO_CHAIN_ID="pearl-1";
async function pay(quote:{id:string;asset:string;amount:string;network?:string},suffix:string){const paymentId=`pay_filecoin_${suffix.padEnd(12,"x")}`;await savePayment({id:crypto.randomUUID(),paymentId,fingerprint:suffix.padEnd(64,"a"),nonce:`nonce_${suffix.padEnd(16,"n")}`,txHash:`HASH-${suffix}`,network:quote.network||"gno:pearl-1",payer:`g1${"q".repeat(38)}`,payTo:merchant,asset:quote.asset,amount:quote.amount,status:"settled",error:null,serviceQuoteId:quote.id,createdAt:new Date().toISOString()});return paymentId}
test("mock upload, paid search and retrieval preserve CID integrity",async()=>{process.env.FILECOIN_MOCK="true";const bytes=Buffer.from("content addressed agent memory"),metadata={filename:"memory.txt",contentType:"text/plain",tags:["agent","memory"],retentionDays:30,replicas:2},upload=await offerUpload(bytes,metadata,"https://storage.test/upload"),uploaded=await executeUpload({bytes,metadata,quoteId:upload.quote.id,paymentId:await pay(upload.quote,"upload"),requestId:"idem_filecoin_upload_1"}) as {cid:string;status:string};assert.equal(uploaded.cid,upload.cid);assert.equal(uploaded.status,"active");const searchRequest={query:"memory",tags:["agent"],limit:10},search=await offerSearch(searchRequest,"https://storage.test/search"),results=await executeSearch({request:searchRequest,quoteId:search.quote.id,paymentId:await pay(search.quote,"search"),requestId:"idem_filecoin_search_1"}) as {results:Array<{cid:string}>};assert.equal(results.results[0].cid,upload.cid);const retrieval=await offerRetrieval(upload.cid,"https://storage.test/cids/x"),download=await executeRetrieval({cid:upload.cid,quoteId:retrieval.quote.id,paymentId:await pay(retrieval.quote,"retrieve"),requestId:"idem_filecoin_get_1"});assert.equal(Buffer.from(download.bytes).toString(),bytes.toString())});
