import test from "node:test";
import assert from "node:assert/strict";
import {decodeTxMessages,MsgCall} from "@gnolang/gno-js-client";
import {PubKeySecp256k1,Secp256k1PubKeyType,Tx,Wallet} from "@gnolang/tm2-js-client";
import {encodeSignedEnvelope,gnoAddressFromPubkey,verifyGnoPayment} from "../lib/gno.ts";
import type {PaymentPayload,PaymentRequirements} from "../lib/domain.ts";
const payer="g1"+"q".repeat(38),payTo="g1"+"p".repeat(38),now=Math.floor(Date.now()/1000);
const req:PaymentRequirements={scheme:"exact",network:"gno:staging",asset:"gno.land/r/gnoland/wugnot",amount:"1000",payTo,maxTimeoutSeconds:60,resource:"https://api.test/data",extra:{chainId:"staging",denom:"ugnot",resourceHash:"a".repeat(64),expiresAt:now+60,nonce:"nonce_1234567890abcdef"}};
const contractPath=`gno.land/r/${payer}/g402pay`,realmReq:PaymentRequirements={...req,asset:"ugnot",extra:{...req.extra,paymentMode:"realm",contractPath}};
function signedTx(to=payTo,amount="1000"){const message={caller:payer,send:"",max_deposit:"",pkg_path:req.asset,func:"Transfer",args:[to,amount]},tx=Tx.create({messages:[{type_url:"/vm.m_call",value:MsgCall.encode(message).finish()}],fee:{gas_fee:"1000000ugnot",gas_wanted:1000000n},signatures:[{pub_key:{type_url:Secp256k1PubKeyType,value:PubKeySecp256k1.encode({key:Buffer.concat([Buffer.from([2]),Buffer.alloc(32,1)])}).finish()},signature:Buffer.alloc(64)}],memo:`g402:pay_1234567890abcdef:${req.extra.nonce}:${req.extra.resourceHash}`});return encodeSignedEnvelope({encodedTransaction:Buffer.from(Tx.encode(tx).finish()).toString("base64"),chainId:"staging",accountNumber:"1",sequence:"2"})}
function payload(tx=signedTx()):PaymentPayload{return{x402Version:2,scheme:"exact",network:"gno:staging",payload:{signedTx:tx,payer,paymentId:"pay_1234567890abcdef",createdAt:now}}}
function realmSignedTx(input:{to?:string;amount?:string;resourceHash?:string;nonce?:string;send?:string;path?:string}={}){const to=input.to??payTo,amount=input.amount??"1000",resourceHash=input.resourceHash??realmReq.extra.resourceHash,nonce=input.nonce??realmReq.extra.nonce,send=input.send??`${amount}ugnot`,path=input.path??contractPath,message={caller:payer,send,max_deposit:"",pkg_path:path,func:"Pay",args:["pay_1234567890abcdef",to,amount,resourceHash,nonce]},tx=Tx.create({messages:[{type_url:"/vm.m_call",value:MsgCall.encode(message).finish()}],fee:{gas_fee:"1000000ugnot",gas_wanted:1000000n},signatures:[{pub_key:{type_url:Secp256k1PubKeyType,value:PubKeySecp256k1.encode({key:Buffer.concat([Buffer.from([2]),Buffer.alloc(32,1)])}).finish()},signature:Buffer.alloc(64)}],memo:`g402:pay_1234567890abcdef:${realmReq.extra.nonce}:${realmReq.extra.resourceHash}`});return encodeSignedEnvelope({encodedTransaction:Buffer.from(Tx.encode(tx).finish()).toString("base64"),chainId:"staging",accountNumber:"1",sequence:"2"})}
test("accepts exact encoded GRC20 transaction structure",()=>assert.equal(verifyGnoPayment(payload(),req,Date.now(),{skipCrypto:true}).isValid,true));
test("rejects recipient substitution",()=>assert.equal(verifyGnoPayment(payload(signedTx("g1"+"z".repeat(38))),req,Date.now(),{skipCrypto:true}).invalidReason,"payment_terms_mismatch"));
test("rejects amount substitution",()=>assert.equal(verifyGnoPayment(payload(signedTx(payTo,"999")),req,Date.now(),{skipCrypto:true}).invalidReason,"payment_terms_mismatch"));
test("rejects signer whose public key does not own payer",()=>assert.equal(verifyGnoPayment(payload(),req).invalidReason,"public_key_mismatch"));
test("accepts exact g402pay realm call",()=>assert.equal(verifyGnoPayment(payload(realmSignedTx()),realmReq,Date.now(),{skipCrypto:true}).isValid,true));
test("rejects g402pay recipient substitution",()=>assert.equal(verifyGnoPayment(payload(realmSignedTx({to:`g1${"z".repeat(38)}`})),realmReq,Date.now(),{skipCrypto:true}).invalidReason,"payment_terms_mismatch"));
test("rejects g402pay send amount substitution",()=>assert.equal(verifyGnoPayment(payload(realmSignedTx({send:"999ugnot"})),realmReq,Date.now(),{skipCrypto:true}).invalidReason,"payment_terms_mismatch"));
test("rejects g402pay resource binding substitution",()=>assert.equal(verifyGnoPayment(payload(realmSignedTx({resourceHash:"b".repeat(64)})),realmReq,Date.now(),{skipCrypto:true}).invalidReason,"payment_terms_mismatch"));
test("derives canonical g bech32 address",()=>assert.match(gnoAddressFromPubkey(Buffer.concat([Buffer.from([2]),Buffer.alloc(32,1)])),/^g1[023456789acdefghjklmnpqrstuvwxyz]{38}$/));
test("verifies a transaction signed by the official TM2 SDK",async()=>{const wallet=await Wallet.fromPrivateKey(new Uint8Array(32).fill(7),{addressPrefix:"g"}),address=await wallet.getAddress(),paymentId="pay_official_sdk_vector",memo=`g402:${paymentId}:${req.extra.nonce}:${req.extra.resourceHash}`;wallet.connect({getStatus:async()=>({node_info:{network:"staging"}}),getAccount:async()=>({BaseAccount:{account_number:"9",sequence:"3"}})} as never);const unsigned=Tx.create({messages:[{type_url:"/vm.m_call",value:MsgCall.encode({caller:address,send:"",max_deposit:"",pkg_path:req.asset,func:"Transfer",args:[payTo,req.amount]}).finish()}],fee:{gas_fee:"1000000ugnot",gas_wanted:1000000n},signatures:[],memo}),signed=await wallet.signTransaction(unsigned,decodeTxMessages,{accountNumber:"9",sequence:"3"}),encoded=encodeSignedEnvelope({encodedTransaction:Buffer.from(Tx.encode(signed).finish()).toString("base64"),chainId:"staging",accountNumber:"9",sequence:"3"}),result=verifyGnoPayment({x402Version:2,scheme:"exact",network:"gno:staging",payload:{signedTx:encoded,payer:address,paymentId,createdAt:now}},req);assert.deepEqual(result,{isValid:true,payer:address})});
