import {createPublicKey,verify as cryptoVerify} from "node:crypto";
import {rawSecp256k1PubkeyToRawAddress} from "@cosmjs/amino";
import {toBech32} from "@cosmjs/encoding";
import {AuthInfo,SignDoc,TxBody,TxRaw} from "cosmjs-types/cosmos/tx/v1beta1/tx";
import {PubKey} from "cosmjs-types/cosmos/crypto/secp256k1/keys";
import {MsgSend} from "cosmjs-types/cosmos/bank/v1beta1/tx";
import {MsgTransfer} from "cosmjs-types/ibc/applications/transfer/v1/tx";
import type {CosmosPayload,CosmosRequirements} from "./domain.ts";
import type {CosmosChain} from "./registry.ts";
export function decodeCosmosTx(payload:CosmosPayload){let raw;try{raw=TxRaw.decode(Buffer.from(payload.payload.txBytes,"base64"))}catch{throw new Error("cosmos_tx_decode_failed")}if(raw.signatures.length!==1)throw new Error("cosmos_single_signature_required");const body=TxBody.decode(raw.bodyBytes),auth=AuthInfo.decode(raw.authInfoBytes);if(body.messages.length!==1||auth.signerInfos.length!==1)throw new Error("cosmos_single_message_required");const signer=auth.signerInfos[0],any=signer.publicKey;if(!any||any.typeUrl!=="/cosmos.crypto.secp256k1.PubKey")throw new Error("cosmos_secp256k1_required");if(signer.modeInfo?.single?.mode!==1)throw new Error("cosmos_direct_sign_required");const publicKey=PubKey.decode(any.value).key,signDoc=SignDoc.encode({bodyBytes:raw.bodyBytes,authInfoBytes:raw.authInfoBytes,chainId:"",accountNumber:BigInt(payload.payload.accountNumber)}).finish();return {raw,body,auth,signer,publicKey,signature:raw.signatures[0],signDoc}}
function verifySignature(signBytes:Uint8Array,signature:Uint8Array,keyBytes:Uint8Array){try{if(signature.length!==64||keyBytes.length!==33)return false;const prefix=Buffer.from("3036301006072a8648ce3d020106052b8104000a032200","hex"),key=createPublicKey({key:Buffer.concat([prefix,Buffer.from(keyBytes)]),format:"der",type:"spki"});return cryptoVerify("sha256",signBytes,{key,dsaEncoding:"ieee-p1363"},signature)}catch{return false}}
export function verifyCosmosPayment(payload:CosmosPayload,req:CosmosRequirements,chain:CosmosChain,now=Date.now(),skipCrypto=false){try{if(payload.network!==req.network||chain.caip2!==req.network)return {valid:false,reason:"network_mismatch"};if(chain.chainId!==req.extra.chainId)return {valid:false,reason:"chain_id_mismatch"};if(Math.abs(now/1000-payload.payload.createdAt)>req.maxTimeoutSeconds||now/1000>req.extra.expiresAt)return {valid:false,reason:"payment_expired"};if(!chain.denoms.includes(req.asset))return {valid:false,reason:"denom_not_registered"};const tx=decodeCosmosTx(payload),message=tx.body.messages[0],address=toBech32(chain.bech32Prefix,rawSecp256k1PubkeyToRawAddress(tx.publicKey));if(address!==payload.payload.signer)return {valid:false,reason:"signer_mismatch"};let okay=false;if(req.extra.transferType==="bank"&&message.typeUrl==="/cosmos.bank.v1beta1.MsgSend"){const msg=MsgSend.decode(message.value);okay=msg.fromAddress===address&&msg.toAddress===req.payTo&&msg.amount.length===1&&msg.amount[0].denom===req.asset&&msg.amount[0].amount===req.amount}else if(req.extra.transferType==="ibc"&&message.typeUrl==="/ibc.applications.transfer.v1.MsgTransfer"){const msg=MsgTransfer.decode(message.value);okay=msg.sender===address&&msg.receiver===req.payTo&&msg.sourcePort==="transfer"&&msg.sourceChannel===req.extra.sourceChannel&&msg.token?.denom===req.asset&&msg.token.amount===req.amount&&msg.timeoutTimestamp>BigInt(now)*1_000_000n}if(!okay)return {valid:false,reason:"payment_terms_mismatch"};if(tx.body.memo!==`x402:${payload.payload.paymentId}:${req.extra.nonce}:${req.extra.resourceHash}`)return {valid:false,reason:"memo_binding_mismatch"};if((tx.auth.fee?.granter||"")!==(req.extra.feeGranter||""))return {valid:false,reason:"fee_granter_mismatch"};const signBytes=SignDoc.encode({bodyBytes:tx.raw.bodyBytes,authInfoBytes:tx.raw.authInfoBytes,chainId:chain.chainId,accountNumber:BigInt(payload.payload.accountNumber)}).finish();if(!skipCrypto&&!verifySignature(signBytes,tx.signature,tx.publicKey))return {valid:false,reason:"invalid_signature"};return {valid:true,signer:address,sequence:String(tx.signer.sequence),txBytes:payload.payload.txBytes}}catch(e){return {valid:false,reason:e instanceof Error?e.message:"cosmos_invalid_tx"}}}
