import {createHash} from "node:crypto";
import {cosmosFingerprint,type CosmosPayload,type CosmosRequirements} from "./domain.ts";
import {verifyCosmosPayment} from "./codec.ts";
import {assertCosmosSettlement,getChain} from "./registry.ts";
import {cosmosUsage,getCosmosPolicy,claimCosmosPayment,updateCosmosPayment} from "./store.ts";
import {evaluateCosmosPolicy} from "./policy.ts";
import {alertOps,metrics} from "../../../lib/observability.ts";
export async function verifyCosmos(payload:CosmosPayload,req:CosmosRequirements,skipCrypto=false){const chain=getChain(payload.network),result=verifyCosmosPayment(payload,req,chain,Date.now(),skipCrypto);if(!result.valid)return result;if(req.extra.agentId){const policy=await getCosmosPolicy(req.extra.agentId);if(!policy)return {valid:false,reason:"cosmos_policy_missing"};const decision=evaluateCosmosPolicy(policy,req,await cosmosUsage(req.extra.agentId));if(!decision.allowed)return {valid:false,reason:decision.reason}}return result}
export async function settleCosmos(payload:CosmosPayload,req:CosmosRequirements,rpcOverride?:string,skipCrypto=false){const chain=getChain(payload.network);assertCosmosSettlement(chain);const verified=await verifyCosmos(payload,req,skipCrypto);if(!verified.valid||!("sequence" in verified))throw new Error(verified.reason);const payment={id:crypto.randomUUID(),paymentId:payload.payload.paymentId,fingerprint:cosmosFingerprint(payload,req),nonce:req.extra.nonce,network:req.network,chainId:req.extra.chainId,signer:payload.payload.signer,recipient:req.payTo,denom:req.asset,amount:req.amount,transferType:req.extra.transferType,agentId:req.extra.agentId,sequence:String(verified.sequence),status:"settling" as const,createdAt:new Date().toISOString()},claim=await claimCosmosPayment(payment);if(!claim.claimed)return {success:claim.existing?.status==="settled",transaction:claim.existing?.txHash,replayed:true,errorReason:claim.existing?.error||claim.existing?.status};try{const response=await fetch(rpcOverride||chain.rpc,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:crypto.randomUUID(),method:"broadcast_tx_commit",params:{tx:payload.payload.txBytes}}),signal:AbortSignal.timeout(60_000)}),body=await response.json() as {result?:{hash?:string;check_tx?:{code?:number;log?:string};deliver_tx?:{code?:number;log?:string}};error?:{message?:string}};if(body.error||!body.result)throw new Error(body.error?.message||"cosmos_rpc_error");const code=body.result.check_tx?.code||body.result.deliver_tx?.code||0;if(code!==0)throw new Error(body.result.deliver_tx?.log||body.result.check_tx?.log||`chain_code_${code}`);const hash=body.result.hash||createHash("sha256").update(Buffer.from(payload.payload.txBytes,"base64")).digest("hex").toUpperCase();await updateCosmosPayment(payment.paymentId,"settled",hash);metrics.inc("cosmos_settlements",{network:req.network,status:"success",type:req.extra.transferType});return {success:true,transaction:hash,network:req.network}}catch(e){const message=e instanceof Error?e.message:String(e);await updateCosmosPayment(payment.paymentId,"failed",undefined,message);metrics.inc("cosmos_settlements",{network:req.network,status:"failed"});void alertOps("Cosmos settlement failed",{network:req.network,paymentId:payment.paymentId,message});throw e}}
