"use client";
import {encodePubkey,makeAuthInfoBytes,type OfflineDirectSigner} from "@cosmjs/proto-signing";
import {fromBase64} from "@cosmjs/encoding";
import {TxBody,TxRaw,type SignDoc} from "cosmjs-types/cosmos/tx/v1beta1/tx";
import {MsgSend} from "cosmjs-types/cosmos/bank/v1beta1/tx";
import {MsgTransfer} from "cosmjs-types/ibc/applications/transfer/v1/tx";
import type {CosmosRequirements} from "./domain.ts";
declare global{interface Window{keplr?:{enable(chainId:string):Promise<void>;getOfflineSigner(chainId:string):OfflineDirectSigner}}}
function toBase64(bytes:Uint8Array){let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
export async function signWithKeplr(req:CosmosRequirements,paymentId:string,input:{accountNumber:number;sequence:number;feeAmount:Array<{denom:string;amount:string}>;gasLimit:number}){if(!window.keplr)throw new Error("keplr_not_installed");await window.keplr.enable(req.extra.chainId);const signer=window.keplr.getOfflineSigner(req.extra.chainId);if(!signer.signDirect)throw new Error("keplr_direct_sign_required");const accounts=await signer.getAccounts();if(accounts.length!==1)throw new Error("keplr_account_ambiguous");const account=accounts[0],message=req.extra.transferType==="bank"?{typeUrl:"/cosmos.bank.v1beta1.MsgSend",value:MsgSend.encode({fromAddress:account.address,toAddress:req.payTo,amount:[{denom:req.asset,amount:req.amount}]}).finish()}:{typeUrl:"/ibc.applications.transfer.v1.MsgTransfer",value:MsgTransfer.encode({sourcePort:"transfer",sourceChannel:req.extra.sourceChannel||"",token:{denom:req.asset,amount:req.amount},sender:account.address,receiver:req.payTo,timeoutHeight:{revisionNumber:0n,revisionHeight:0n},timeoutTimestamp:BigInt(Date.now()+10*60_000)*1_000_000n,memo:"",encoding:""}).finish()},memo=`x402:${paymentId}:${req.extra.nonce}:${req.extra.resourceHash}`,bodyBytes=TxBody.encode(TxBody.fromPartial({messages:[message],memo})).finish(),authInfoBytes=makeAuthInfoBytes([{pubkey:encodePubkey({type:"tendermint/PubKeySecp256k1",value:toBase64(account.pubkey)}),sequence:input.sequence}],input.feeAmount,input.gasLimit,req.extra.feeGranter,undefined),signDoc:SignDoc={bodyBytes,authInfoBytes,chainId:req.extra.chainId,accountNumber:BigInt(input.accountNumber)},signed=await signer.signDirect(account.address,signDoc),tx=TxRaw.encode({bodyBytes:signed.signed.bodyBytes,authInfoBytes:signed.signed.authInfoBytes,signatures:[fromBase64(signed.signature.signature)]}).finish();return {txBytes:toBase64(tx),signer:account.address,accountNumber:String(input.accountNumber),paymentId,createdAt:Math.floor(Date.now()/1000)}}
