import Link from "next/link";
import { listPayments,type PaymentRecord } from "@/lib/store";
import { getScanStatus } from "@/lib/scan";
export const dynamic="force-dynamic";
export default async function Home(){const payments=await listPayments(200),recent=payments.slice(0,8),settled=payments.filter(p=>p.status==="settled"),volume=settled.reduce((sum,p)=>sum+BigInt(p.amount),0n),realmMode=process.env.G402_PAYMENT_MODE==="realm";let scan:null|Awaited<ReturnType<typeof getScanStatus>>=null;try{scan=await getScanStatus()}catch{}const configured=Boolean(scan)&&process.env.G402_ENABLE_SETTLEMENT==="true";return <>
  <section className="hero"><div><div className="eyebrow">Working Gno testnet payment infrastructure</div><h1>Facilitate. Settle. <em>Scan.</em></h1><p>Adena가 서명한 x402 결제를 검증하고 Pearl 테스트넷에 정산한 뒤, 블록과 영수증을 하나의 영속 원장에 색인합니다.</p><div className="heroActions"><Link className="button" href="/wallet">Run paid API test</Link><Link className="button secondary" href="/scan">Open g402 Scan</Link></div></div><div className="heroAside"><div className="statusLine"><span>Facilitator</span><b className={configured?"success":"pending"}>{configured?"Configured":"Configuration required"}</b></div><div className="statusLine"><span>Settlement rail</span><b>{realmMode?"g402pay realm":"WUGNOT direct"} · Pearl</b></div><div className="statusLine"><span>Indexed height</span><b>{scan?.indexedHeight||"—"}</b></div><div className="statusLine"><span>Mainnet</span><b className="pending">Safety locked</b></div></div></section>
  <section className="grid stats"><div className="card stat"><label>SETTLED VOLUME</label><strong>{volume.toString()}</strong><small>atomic units</small></div><div className="card stat"><label>CHAIN TRANSACTIONS</label><strong>{scan?.transactions||0}</strong></div><div className="card stat"><label>G402 PAYMENTS</label><strong>{settled.length}</strong></div><div className="card stat"><label>INDEX LAG</label><strong>{scan?.lag??"—"}</strong><small>blocks</small></div></section>
  <section className="grid layout"><div className="card"><div className="sectionTitle"><h2>Recent payments</h2><Link href="/scan">Search chain →</Link></div><PaymentTable payments={recent}/></div><div className="card"><div className="sectionTitle"><h2>Enforced controls</h2></div><div className="activity"><Activity text="Issued challenge binds terms and expiry" time="D1"/><Activity text="Nonce and payment ID are single-use" time="atomic"/><Activity text="RPC chain ID pinned before broadcast" time="fail-closed"/><Activity text="Reorgs revert orphaned receipts" time="indexed"/></div></div></section>
  </>}
function Activity({text,time}:{text:string,time:string}){return <div className="activityItem"><i className="dot"/><div><p>{text}</p><small>{time}</small></div></div>}
function short(value:string){return value.length>15?`${value.slice(0,7)}…${value.slice(-5)}`:value}
export function PaymentTable({payments}:{payments:PaymentRecord[]}){return <div className="tableWrap"><table className="table"><thead><tr><th>Payment</th><th>Created</th><th>Route</th><th>Amount</th><th>Block</th><th>Status</th></tr></thead><tbody>{payments.length?payments.map(p=><tr key={p.paymentId}><td className="mono">{short(p.paymentId)}</td><td>{new Date(p.createdAt).toLocaleString()}</td><td className="mono">{short(p.payer)} → {short(p.payTo)}</td><td>{p.amount}</td><td>{p.blockHeight?`#${p.blockHeight} · ${p.confirmations||0} conf`:"—"}</td><td><span className={(p.status==="settled"?"success":p.status==="failed"||p.status==="reverted"?"failed":"pending")+" badge"}>{p.status}</span></td></tr>):<tr><td colSpan={6}>No payments yet. Run the paid API test from Adena Wallet.</td></tr>}</tbody></table></div>}
