import Link from "next/link";
import { listPayments,type PaymentRecord } from "@/lib/store";
export const dynamic="force-dynamic";
export default async function Home(){const payments=await listPayments(8),settled=payments.filter(p=>p.status==="settled"),volume=settled.reduce((sum,p)=>sum+BigInt(p.amount),0n);return <>
  <section className="hero"><div><div className="eyebrow">HTTP-native payments for autonomous software</div><h1>The payment rail for <em>Gno agents.</em></h1><p>Verify, settle and observe machine-to-machine payments on Gno.land. Open x402-compatible infrastructure built for auditable agent commerce.</p></div><div className="heroAside"><div className="statusLine"><span>Facilitator</span><b className="success">Operational</b></div><div className="statusLine"><span>Settlement rail</span><b>wugnot · Staging</b></div><div className="statusLine"><span>Indexed records</span><b>{payments.length}</b></div><div className="statusLine"><span>Mainnet</span><b className="pending">Safety locked</b></div></div></section>
  <section className="grid stats"><div className="card stat"><label>SETTLED VOLUME</label><strong>{volume.toString()}</strong><small>atomic units</small></div><div className="card stat"><label>RECENT PAYMENTS</label><strong>{payments.length}</strong></div><div className="card stat"><label>FINALIZED</label><strong>{settled.length}</strong></div><div className="card stat"><label>SAFETY MODE</label><strong>STAGING</strong></div></section>
  <section className="grid layout"><div className="card"><div className="sectionTitle"><h2>Live payments</h2><Link href="/payments">View explorer →</Link></div><PaymentTable payments={payments}/></div><div className="card"><div className="sectionTitle"><h2>Operational state</h2></div><div className="activity"><Activity text="Mainnet settlement independently locked" time="fail-closed"/><Activity text="Signed terms bind resource and nonce" time="enforced"/><Activity text="Indexer reconciles canonical blocks" time="worker"/><Activity text="Agent policy precedes broadcast" time="enforced"/></div></div></section>
  </>}
function Activity({text,time}:{text:string,time:string}){return <div className="activityItem"><i className="dot"/><div><p>{text}</p><small>{time}</small></div></div>}
function short(value:string){return value.length>15?`${value.slice(0,7)}…${value.slice(-5)}`:value}
export function PaymentTable({payments}:{payments:PaymentRecord[]}){return <div className="tableWrap"><table className="table"><thead><tr><th>Payment</th><th>Created</th><th>Route</th><th>Asset</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.length?payments.map(p=><tr key={p.paymentId}><td className="mono">{short(p.paymentId)}</td><td>{new Date(p.createdAt).toLocaleString()}</td><td className="mono">{short(p.payer)} → {short(p.payTo)}</td><td className="mono">{short(p.asset)}</td><td>{p.amount}</td><td><span className={(p.status==="settled"?"success":p.status==="failed"||p.status==="reverted"?"failed":"pending")+" badge"}>{p.status}</span></td></tr>):<tr><td colSpan={6}>No indexed payments yet. Start the staging worker or sign the paid API sample.</td></tr>}</tbody></table></div>}
