import type { PaymentRequirements } from "./domain.ts";
export type AdenaResponse<T>={code:number;status:"success"|"failure";type:string;message:string;data:T};
export type AdenaAccount={status?:string;address:string;coins:string;publicKey?:{"@type":string;value:string};accountNumber:string;sequence:string;chainId:string};
export type AdenaAccountResponse={status?:string;address?:string;coins?:unknown;publicKey?:{"@type":string;value:string};public_key?:{"@type":string;value:string};accountNumber?:string|number;account_number?:string|number;sequence?:string|number;chainId?:string;chain_id?:string};
export type AdenaSignData={signed?:unknown;document?:unknown;signature:unknown};
export type AdenaProvider={AddEstablish(name:string):Promise<AdenaResponse<Record<string,never>>>;GetAccount():Promise<AdenaResponse<AdenaAccountResponse>>;Sign(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<AdenaSignData>>;SignTx?(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<{encodedTransaction:string}>>;DoContract(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<{hash:string;height:string}>>};
declare global{interface Window{adena?:AdenaProvider}}
export function getAdena():AdenaProvider{if(typeof window==="undefined"||!window.adena)throw new Error("adena_not_installed");return window.adena}
export function normalizeAdenaAccount(data:AdenaAccountResponse):AdenaAccount{const address=String(data.address||""),accountNumber=String(data.accountNumber??data.account_number??""),sequence=String(data.sequence??""),chainId=String(data.chainId??data.chain_id??"");if(!address||!accountNumber||!sequence||!chainId)throw new Error("adena_account_shape_invalid");return {status:data.status,address,coins:typeof data.coins==="string"?data.coins:JSON.stringify(data.coins??[]),publicKey:data.publicKey??data.public_key,accountNumber,sequence,chainId}}
export async function connectAdena(){const provider=getAdena(),connection=await provider.AddEstablish("g402 Agent Wallet");if(connection.status!=="success")throw new Error(connection.message||"adena_connection_rejected");const account=await provider.GetAccount();if(account.status!=="success")throw new Error(account.message||"adena_account_unavailable");return normalizeAdenaAccount(account.data)}
export async function signG402Payment(account:AdenaAccount,requirements:PaymentRequirements,paymentId:string){const provider=getAdena(),latestResponse=await provider.GetAccount();if(latestResponse.status!=="success")throw new Error(latestResponse.message||"adena_account_unavailable");const latest=normalizeAdenaAccount(latestResponse.data);if(latest.address!==account.address)throw new Error("adena_account_changed");if(latest.chainId!==requirements.extra.chainId)throw new Error("adena_network_mismatch");const memo=`g402:${paymentId}:${requirements.extra.nonce}:${requirements.extra.resourceHash}`,realmMode=requirements.extra.paymentMode==="realm";if(realmMode&&!requirements.extra.contractPath)throw new Error("contract_path_required");const isNative=!requirements.asset.includes("/");const message=realmMode?{type:"/vm.m_call",value:{caller:latest.address,send:`${requirements.amount}${requirements.extra.denom}`,max_deposit:"",pkg_path:requirements.extra.contractPath!,func:"Pay",args:[paymentId,requirements.payTo,requirements.amount,requirements.extra.resourceHash,requirements.extra.nonce]}}:isNative?{type:"/bank.MsgSend",value:{from_address:latest.address,to_address:requirements.payTo,amount:`${requirements.amount}${requirements.extra.denom}`}}:{type:"/vm.m_call",value:{caller:latest.address,send:"",max_deposit:"",pkg_path:requirements.asset,func:"Transfer",args:[requirements.payTo,requirements.amount]}};if(!provider.SignTx)throw new Error("adena_signtx_unavailable");const response=await provider.SignTx({messages:[message],memo},true);if(response.status!=="success"||!response.data.encodedTransaction)throw new Error(response.message||"adena_signature_rejected");const envelope={encodedTransaction:response.data.encodedTransaction,chainId:latest.chainId,accountNumber:latest.accountNumber,sequence:latest.sequence},bytes=new TextEncoder().encode(JSON.stringify(envelope));let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
