import type { PaymentRequirements } from "./domain.ts";
export type AdenaResponse<T>={code:number;status:"success"|"failure";type:string;message:string;data:T};
export type AdenaAccount={status:string;address:string;coins:string;public_key?:{"@type":string;value:string};account_number:string;sequence:string;chainId:string};
export type AdenaSignData={signed?:unknown;document?:unknown;signature:unknown};
export type AdenaProvider={AddEstablish(name:string):Promise<AdenaResponse<Record<string,never>>>;GetAccount():Promise<AdenaResponse<AdenaAccount>>;Sign(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<AdenaSignData>>;SignTx?(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<{encodedTransaction:string}>>;DoContract(tx:{messages:Array<{type:string;value:Record<string,unknown>}>;memo?:string},isNotification?:boolean):Promise<AdenaResponse<{hash:string;height:string}>>};
declare global{interface Window{adena?:AdenaProvider}}
export function getAdena():AdenaProvider{if(typeof window==="undefined"||!window.adena)throw new Error("adena_not_installed");return window.adena}
export async function connectAdena(){const provider=getAdena(),connection=await provider.AddEstablish("g402 Agent Wallet");if(connection.status!=="success")throw new Error(connection.message||"adena_connection_rejected");const account=await provider.GetAccount();if(account.status!=="success")throw new Error(account.message||"adena_account_unavailable");return account.data}
export async function signG402Payment(account:AdenaAccount,requirements:PaymentRequirements,paymentId:string){if(account.chainId!==requirements.extra.chainId)throw new Error("adena_network_mismatch");const memo=`g402:${paymentId}:${requirements.extra.nonce}:${requirements.extra.resourceHash}`;const isNative=!requirements.asset.includes("/"),message=isNative?{type:"/bank.MsgSend",value:{from_address:account.address,to_address:requirements.payTo,amount:`${requirements.amount}${requirements.extra.denom}`}}:{type:"/vm.m_call",value:{caller:account.address,send:"",max_deposit:"",pkg_path:requirements.asset,func:"Transfer",args:[requirements.payTo,requirements.amount]}};const provider=getAdena();if(!provider.SignTx)throw new Error("adena_signtx_unavailable");const response=await provider.SignTx({messages:[message],memo},true);if(response.status!=="success"||!response.data.encodedTransaction)throw new Error(response.message||"adena_signature_rejected");const envelope={encodedTransaction:response.data.encodedTransaction,chainId:account.chainId,accountNumber:account.account_number,sequence:account.sequence},bytes=new TextEncoder().encode(JSON.stringify(envelope));let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
