import {createHash,createPublicKey,verify as cryptoVerify} from "node:crypto";
import {decodeTxMessages} from "@gnolang/gno-js-client";
import {PubKeySecp256k1,Secp256k1PubKeyType,Tx} from "@gnolang/tm2-js-client";
import {broadcastTxCommitSuccess,Tm2Client,type RpcClient} from "@gnolang/tm2-rpc";
import type {PaymentPayload,PaymentRequirements,SettlementResult,VerificationResult} from "./domain.ts";

export type GnoSignDoc={chain_id:string;account_number:string;sequence:string;fee:{gas_fee:string;gas_wanted:string};msgs:Array<Record<string,unknown>>;memo:string};
export type SignedGnoEnvelope={encodedTransaction:string;chainId:string;accountNumber:string;sequence:string};
export type DecodedGnoTransaction={envelope:SignedGnoEnvelope;signDoc:GnoSignDoc;signature:Buffer;publicKey:Buffer};
function sortJson(value:unknown):unknown{if(Array.isArray(value))return value.map(sortJson);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sortJson(v)]));return value}
export function canonicalSignBytes(doc:GnoSignDoc):Buffer{return Buffer.from(JSON.stringify(sortJson(doc)).replace(/</g,"\\u003c").replace(/>/g,"\\u003e").replace(/&/g,"\\u0026"),"utf8")}
export function encodeSignedEnvelope(envelope:SignedGnoEnvelope){return Buffer.from(JSON.stringify(envelope)).toString("base64url")}
export function decodeSignedTransaction(encoded:string):DecodedGnoTransaction{let envelope:SignedGnoEnvelope;try{envelope=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8")) as SignedGnoEnvelope}catch{throw new Error("malformed_transaction_encoding")}if(!envelope.encodedTransaction||!/^[A-Za-z0-9+/=_-]+$/.test(envelope.encodedTransaction)||!/^\d+$/.test(envelope.accountNumber)||!/^\d+$/.test(envelope.sequence)||!envelope.chainId)throw new Error("malformed_transaction");let tx;try{tx=Tx.decode(Buffer.from(envelope.encodedTransaction.replace(/-/g,"+").replace(/_/g,"/"),"base64"))}catch{throw new Error("transaction_decode_failed")}if(tx.messages.length!==1||tx.signatures.length!==1||!tx.fee)throw new Error("unsupported_transaction_shape");const sig=tx.signatures[0];if(!sig.pub_key||sig.pub_key.type_url!==Secp256k1PubKeyType)throw new Error("unsupported_public_key");const publicKey=Buffer.from(PubKeySecp256k1.decode(sig.pub_key.value).key),signature=Buffer.from(sig.signature);if(publicKey.length!==33||signature.length!==64)throw new Error("invalid_signature_shape");const signDoc:GnoSignDoc={chain_id:envelope.chainId,account_number:envelope.accountNumber,sequence:envelope.sequence,fee:{gas_fee:tx.fee.gas_fee,gas_wanted:tx.fee.gas_wanted.toString(10)},msgs:decodeTxMessages(tx.messages) as Array<Record<string,unknown>>,memo:tx.memo};return {envelope,signDoc,signature,publicKey}}
export function verifyGnoSignature(tx:DecodedGnoTransaction):boolean{try{const prefix=Buffer.from("3036301006072a8648ce3d020106052b8104000a032200","hex"),key=createPublicKey({key:Buffer.concat([prefix,tx.publicKey]),format:"der",type:"spki"});return cryptoVerify("sha256",canonicalSignBytes(tx.signDoc),{key,dsaEncoding:"ieee-p1363"},tx.signature)}catch{return false}}
const CHARS="qpzry9x8gf2tvdw0s3jn54khce6mua7l";
function polymod(values:number[]){let chk=1;for(const value of values){const top=chk>>>25;chk=((chk&0x1ffffff)<<5)^value;for(let i=0;i<5;i++)if((top>>>i)&1)chk^=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3][i]}return chk}
function bits(data:Uint8Array){let acc=0,n=0;const out:number[]=[];for(const value of data){acc=(acc<<8)|value;n+=8;while(n>=5){n-=5;out.push((acc>>>n)&31)}}if(n)out.push((acc<<(5-n))&31);return out}
export function gnoAddressFromPubkey(key:Buffer){if(key.length!==33)throw new Error("invalid_public_key");const payload=createHash("ripemd160").update(createHash("sha256").update(key).digest()).digest(),words=bits(payload),hrp=[3,0,7],sum=polymod([...hrp,...words,0,0,0,0,0,0])^1,check=Array.from({length:6},(_,i)=>(sum>>>(5*(5-i)))&31);return `g1${[...words,...check].map(v=>CHARS[v]).join("")}`}
function terms(msg:Record<string,unknown>){const type=String(msg["@type"]||"");if(type==="/bank.MsgSend")return {kind:"native",payer:String(msg.from_address||""),recipient:String(msg.to_address||""),amount:String(msg.amount||"")};if(type==="/vm.m_call")return {kind:"grc20",payer:String(msg.caller||""),recipient:Array.isArray(msg.args)?String(msg.args[0]||""):"",amount:Array.isArray(msg.args)?String(msg.args[1]||""):"",pkgPath:String(msg.pkg_path||""),func:String(msg.func||""),send:String(msg.send||""),maxDeposit:String(msg.max_deposit||"")};return {kind:"unsupported",payer:"",recipient:"",amount:""}}
export function verifyGnoPayment(payload:PaymentPayload,req:PaymentRequirements,now=Date.now(),options:{skipCrypto?:boolean}={}):VerificationResult{try{if(payload.network!==req.network)return {isValid:false,invalidReason:"network_mismatch"};if(Math.abs(now/1000-payload.payload.createdAt)>req.maxTimeoutSeconds||now/1000>req.extra.expiresAt)return {isValid:false,invalidReason:"payment_expired"};const tx=decodeSignedTransaction(payload.payload.signedTx),t=terms(tx.signDoc.msgs[0]);if(tx.signDoc.chain_id!==req.extra.chainId)return {isValid:false,invalidReason:"chain_id_mismatch"};if(t.payer!==payload.payload.payer)return {isValid:false,invalidReason:"payer_mismatch"};const nativeAsset=req.asset===req.extra.denom&&!req.asset.includes("/"),grc20Asset=req.asset.includes("/");const native=nativeAsset&&t.kind==="native"&&t.recipient===req.payTo&&t.amount===`${req.amount}${req.extra.denom}`,grc20=grc20Asset&&t.kind==="grc20"&&t.pkgPath===req.asset&&t.func==="Transfer"&&t.send===""&&t.maxDeposit===""&&t.recipient===req.payTo&&t.amount===req.amount,args=t.kind==="grc20"?(tx.signDoc.msgs[0].args as unknown[]):[],realm=req.extra.paymentMode==="realm"&&t.kind==="grc20"&&t.pkgPath===req.extra.contractPath&&t.func==="Pay"&&t.send===`${req.amount}${req.extra.denom}`&&t.maxDeposit===""&&args.length===5&&String(args[0])===payload.payload.paymentId&&String(args[1])===req.payTo&&String(args[2])===req.amount&&String(args[3])===req.extra.resourceHash&&String(args[4])===req.extra.nonce;if(!(req.extra.paymentMode==="realm"?realm:(native||grc20)))return {isValid:false,invalidReason:"payment_terms_mismatch"};if(tx.signDoc.memo!==`g402:${payload.payload.paymentId}:${req.extra.nonce}:${req.extra.resourceHash}`)return {isValid:false,invalidReason:"memo_binding_mismatch"};if(!options.skipCrypto){if(gnoAddressFromPubkey(tx.publicKey)!==payload.payload.payer)return {isValid:false,invalidReason:"public_key_mismatch"};if(!verifyGnoSignature(tx))return {isValid:false,invalidReason:"invalid_signature"}}return {isValid:true,payer:payload.payload.payer}}catch(e){return {isValid:false,invalidReason:e instanceof Error?e.message:"invalid_payload"}}}
function hex(bytes:Uint8Array|undefined){return bytes?Buffer.from(bytes).toString("hex").toUpperCase():""}
async function nativeTm2Execute(url:string,request:Parameters<RpcClient["execute"]>[0]):Promise<Awaited<ReturnType<RpcClient["execute"]>>>{
  const endpoint=new URL(url),local=endpoint.hostname==="localhost"||endpoint.hostname==="127.0.0.1";
  if((endpoint.protocol!=="https:"&&!(local&&endpoint.protocol==="http:"))||endpoint.username||endpoint.password||endpoint.hash)throw new Error("invalid_gno_rpc_url");
  let response:Response;
  try{response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(request),redirect:"error",signal:AbortSignal.timeout(10_000)})}catch{throw new Error("gno_rpc_unavailable")}
  if(!response.ok)throw new Error("gno_rpc_unavailable");
  let parsed:unknown;
  try{parsed=await response.json()}catch{throw new Error("gno_rpc_unavailable")}
  if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("gno_rpc_unavailable");
  const body=parsed as {jsonrpc?:unknown;id?:unknown;result?:unknown;error?:unknown};
  if(body.jsonrpc!=="2.0"||body.id!==request.id||body.error||!("result" in body))throw new Error(body.error?`gno_rpc_error:${JSON.stringify(body.error).slice(0,400)}`:"gno_rpc_unavailable");
  return body as Awaited<ReturnType<RpcClient["execute"]>>;
}
export async function connectNativeTm2(url:string):Promise<Tm2Client>{
  const client:RpcClient={disconnect(){},execute:request=>nativeTm2Execute(url,request)};
  return Tm2Client.create(client);
}
function rawRpcHash(value:unknown){if(typeof value!=="string"||!value)return "";if(/^(?:[0-9a-fA-F]{2})+$/.test(value))return value.toUpperCase();try{return Buffer.from(value,"base64").toString("hex").toUpperCase()}catch{return ""}}
async function nativeGnoStatus(url:string){
  const id=crypto.randomUUID(),response=await nativeTm2Execute(url,{jsonrpc:"2.0",id,method:"status",params:{}}),result=response.result as {node_info?:{network?:unknown};sync_info?:{latest_block_height?:unknown;latest_block_hash?:unknown;catching_up?:unknown}};
  if(!result?.node_info||typeof result.node_info.network!=="string"||!result.sync_info||!/^\d+$/.test(String(result.sync_info.latest_block_height??""))||typeof result.sync_info.catching_up!=="boolean")throw new Error("gno_rpc_unavailable");
  return {node_info:{network:result.node_info.network},sync_info:{latest_block_height:String(result.sync_info.latest_block_height),latest_block_hash:rawRpcHash(result.sync_info.latest_block_hash),catching_up:result.sync_info.catching_up}};
}
export function signedTransactionHash(signedEnvelope:string){const raw=decodeSignedTransaction(signedEnvelope).envelope.encodedTransaction;return createHash("sha256").update(Buffer.from(raw.replace(/-/g,"+").replace(/_/g,"/"),"base64")).digest("hex").toUpperCase()}
export class GnoRpcClient{
  private clientPromise:Promise<Tm2Client>|null=null;
  private readonly url:string;
  private readonly clientFactory:(url:string)=>Promise<Tm2Client>;
  private readonly nativeStatus:boolean;
  constructor(url=process.env.GNO_RPC_URL||"https://rpc.pearl.testnets.gno.land",clientFactory?:(url:string)=>Promise<Tm2Client>){this.url=url;this.clientFactory=clientFactory||connectNativeTm2;this.nativeStatus=!clientFactory}
  private client(){return this.clientPromise??=this.clientFactory(this.url)}
  async broadcastTxCommit(signedEnvelope:string,network:string,expectedChainId=process.env.GNO_CHAIN_ID||"pearl-1"):Promise<SettlementResult>{const rawBase64=decodeSignedTransaction(signedEnvelope).envelope.encodedTransaction,raw=Buffer.from(rawBase64.replace(/-/g,"+").replace(/_/g,"/"),"base64"),fallbackHash=createHash("sha256").update(raw).digest("hex").toUpperCase();try{const client=await this.client(),statusNetwork=this.nativeStatus?(await nativeGnoStatus(this.url)).node_info.network:(await client.status()).nodeInfo.network;if(statusNetwork!==expectedChainId)return {success:false,network,transaction:fallbackHash,errorReason:"rpc_chain_id_mismatch"};const result=await client.broadcastTxCommit({tx:raw}),hash=hex(result.hash)||fallbackHash;if(!broadcastTxCommitSuccess(result)){const failure=result.deliverTx?.responseBase.error?.value||result.deliverTx?.responseBase.log||result.checkTx.responseBase.error?.value||result.checkTx.responseBase.log||"chain_rejected";return {success:false,network,transaction:hash,errorReason:failure,pending:false,blockHeight:result.height}}return {success:true,network,transaction:hash,blockHeight:result.height}}catch(e){return {success:false,network,transaction:fallbackHash,errorReason:e instanceof Error?e.message:"rpc_error",pending:true}}}
  async lookupTransaction(hashValue:string,network:string):Promise<SettlementResult|null>{try{const result=await (await this.client()).tx({hash:Buffer.from(hashValue,"hex")}),error=result.result.responseBase.error?.value||"";return {success:!error,network,transaction:hex(result.hash)||hashValue,errorReason:error||undefined,blockHeight:result.height}}catch{return null}}
  async status(){if(this.nativeStatus)return nativeGnoStatus(this.url);const result=await (await this.client()).status();return {node_info:{network:result.nodeInfo.network},sync_info:{latest_block_height:String(result.syncInfo.latestBlockHeight),latest_block_hash:hex(result.syncInfo.latestBlockHash),catching_up:result.syncInfo.catchingUp}}}
  async block(height:number){const result=await (await this.client()).block(height);return {block_id:{hash:hex(result.blockMeta.blockId.hash)},block:{header:{height:String(result.block.header.height),time:result.block.header.time.toISOString(),chain_id:result.block.header.chainId,last_block_id:result.block.header.lastBlockId?{hash:hex(result.block.header.lastBlockId.hash)}:undefined},data:{txs:result.block.txs.map(tx=>Buffer.from(tx).toString("base64"))}}}}
  async blockResults(height:number){const result=await (await this.client()).blockResults(height);return {height:String(result.height),txs_results:result.results.deliverTx.map(tx=>{const error=tx.responseBase.error?.value||"";return {code:error?1:0,log:error||tx.responseBase.log,events:tx.responseBase.events.map(event=>({type:event.type,typeUrl:event["@type"],pkg_path:event.pkg_path,attributes:event.attrs.map(attribute=>({key:attribute.key,value:attribute.value}))}))}})}}
}
