import {createHash,createPublicKey,verify as cryptoVerify} from "node:crypto";
import {decodeTxMessages} from "@gnolang/gno-js-client";
import {PubKeySecp256k1,Secp256k1PubKeyType,Tx} from "@gnolang/tm2-js-client";
import type {PaymentPayload,PaymentRequirements,SettlementResult,VerificationResult} from "./domain.ts";

export type GnoSignDoc={chain_id:string;account_number:string;sequence:string;fee:{gas_fee:string;gas_wanted:string};msgs:Array<Record<string,unknown>>;memo:string};
export type SignedGnoEnvelope={encodedTransaction:string;chainId:string;accountNumber:string;sequence:string};
export type DecodedGnoTransaction={envelope:SignedGnoEnvelope;signDoc:GnoSignDoc;signature:Buffer;publicKey:Buffer};
function sortJson(value:unknown):unknown{if(Array.isArray(value))return value.map(sortJson);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,sortJson(v)]));return value}
export function canonicalSignBytes(doc:GnoSignDoc):Buffer{return Buffer.from(JSON.stringify(sortJson(doc)).replace(/</g,"\\u003c").replace(/>/g,"\\u003e").replace(/&/g,"\\u0026"),"utf8")}
export function encodeSignedEnvelope(envelope:SignedGnoEnvelope){return Buffer.from(JSON.stringify(envelope)).toString("base64url")}
export function decodeSignedTransaction(encoded:string):DecodedGnoTransaction{let envelope:SignedGnoEnvelope;try{envelope=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8")) as SignedGnoEnvelope}catch{throw new Error("malformed_transaction_encoding")}if(!envelope.encodedTransaction||!/^[A-Za-z0-9+/=_-]+$/.test(envelope.encodedTransaction)||!/^\d+$/.test(envelope.accountNumber)||!/^\d+$/.test(envelope.sequence)||!envelope.chainId)throw new Error("malformed_transaction");let tx;try{tx=Tx.decode(Buffer.from(envelope.encodedTransaction.replace(/-/g,"+").replace(/_/g,"/"),"base64"))}catch{throw new Error("transaction_decode_failed")}if(tx.messages.length!==1||tx.signatures.length!==1||!tx.fee)throw new Error("unsupported_transaction_shape");const sig=tx.signatures[0];if(!sig.pub_key||sig.pub_key.type_url!==Secp256k1PubKeyType)throw new Error("unsupported_public_key");const publicKey=Buffer.from(PubKeySecp256k1.decode(sig.pub_key.value).key),signature=Buffer.from(sig.signature);if(publicKey.length!==33||signature.length!==64)throw new Error("invalid_signature_shape");const signDoc:GnoSignDoc={chain_id:envelope.chainId,account_number:envelope.accountNumber,sequence:envelope.sequence,fee:{gas_fee:tx.fee.gas_fee,gas_wanted:tx.fee.gas_wanted.toString(10)},msgs:decodeTxMessages(tx.messages) as Array<Record<string,unknown>>,memo:tx.memo};return {envelope,signDoc,signature,publicKey}}
export function verifyGnoSignature(tx:DecodedGnoTransaction):boolean{try{const prefix=Buffer.from("3036301006072a8648ce3d020106052b8104000a032200","hex"),key=createPublicKey({key:Buffer.concat([prefix,tx.publicKey]),format:"der",type:"spki"});return cryptoVerify("sha256",canonicalSignBytes(tx.signDoc),{key,dsaEncoding:"ieee-p1363"},tx.signature)}catch{return false}}
const CHARS="qpzry9x8gf2tvdw0s3jn54khce6mua7l";
function polymod(values:number[]){let chk=1;for(const value of values){const top=chk>>>25;chk=((chk&0x1ffffff)<<5)^value;for(let i=0;i<5;i++)if((top>>>i)&1)chk^=[0x3b6a57b2,0x26508e6d,0x1ea119fa,0x3d4233dd,0x2a1462b3][i]}return chk}
function bits(data:Uint8Array){let acc=0,n=0;const out:number[]=[];for(const value of data){acc=(acc<<8)|value;n+=8;while(n>=5){n-=5;out.push((acc>>>n)&31)}}if(n)out.push((acc<<(5-n))&31);return out}
export function gnoAddressFromPubkey(key:Buffer){if(key.length!==33)throw new Error("invalid_public_key");const payload=createHash("ripemd160").update(createHash("sha256").update(key).digest()).digest(),words=bits(payload),hrp=[3,0,7],sum=polymod([...hrp,...words,0,0,0,0,0,0])^1,check=Array.from({length:6},(_,i)=>(sum>>>(5*(5-i)))&31);return `g1${[...words,...check].map(v=>CHARS[v]).join("")}`}
function terms(msg:Record<string,unknown>){const type=String(msg["@type"]||"");if(type==="/bank.MsgSend")return {kind:"native",payer:String(msg.from_address||""),recipient:String(msg.to_address||""),amount:String(msg.amount||"")};if(type==="/vm.m_call")return {kind:"grc20",payer:String(msg.caller||""),recipient:Array.isArray(msg.args)?String(msg.args[0]||""):"",amount:Array.isArray(msg.args)?String(msg.args[1]||""):"",pkgPath:String(msg.pkg_path||""),func:String(msg.func||""),send:String(msg.send||""),maxDeposit:String(msg.max_deposit||"")};return {kind:"unsupported",payer:"",recipient:"",amount:""}}
export function verifyGnoPayment(payload:PaymentPayload,req:PaymentRequirements,now=Date.now(),options:{skipCrypto?:boolean}={}):VerificationResult{try{if(payload.network!==req.network)return {isValid:false,invalidReason:"network_mismatch"};if(Math.abs(now/1000-payload.payload.createdAt)>req.maxTimeoutSeconds||now/1000>req.extra.expiresAt)return {isValid:false,invalidReason:"payment_expired"};const tx=decodeSignedTransaction(payload.payload.signedTx),t=terms(tx.signDoc.msgs[0]);if(tx.signDoc.chain_id!==req.extra.chainId)return {isValid:false,invalidReason:"chain_id_mismatch"};if(t.payer!==payload.payload.payer)return {isValid:false,invalidReason:"payer_mismatch"};const native=t.kind==="native"&&t.recipient===req.payTo&&t.amount===`${req.amount}${req.extra.denom}`,grc20=t.kind==="grc20"&&t.pkgPath===req.asset&&t.func==="Transfer"&&t.send===""&&t.maxDeposit===""&&t.recipient===req.payTo&&t.amount===req.amount;if(!native&&!grc20)return {isValid:false,invalidReason:"payment_terms_mismatch"};if(tx.signDoc.memo!==`g402:${payload.payload.paymentId}:${req.extra.nonce}:${req.extra.resourceHash}`)return {isValid:false,invalidReason:"memo_binding_mismatch"};if(!options.skipCrypto){if(gnoAddressFromPubkey(tx.publicKey)!==payload.payload.payer)return {isValid:false,invalidReason:"public_key_mismatch"};if(!verifyGnoSignature(tx))return {isValid:false,invalidReason:"invalid_signature"}}return {isValid:true,payer:payload.payload.payer}}catch(e){return {isValid:false,invalidReason:e instanceof Error?e.message:"invalid_payload"}}}
export class GnoRpcClient{constructor(private readonly url=process.env.GNO_RPC_URL||"https://rpc.staging.gno.land:443"){}private async rpc<T>(method:string,params:Record<string,unknown>):Promise<T>{const res=await fetch(this.url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:crypto.randomUUID(),method,params}),signal:AbortSignal.timeout(25_000)});if(!res.ok)throw new Error(`rpc_http_${res.status}`);const body=await res.json() as {result?:T;error?:{message?:string}};if(body.error)throw new Error(body.error.message||"rpc_error");if(!body.result)throw new Error("rpc_empty_result");return body.result}async broadcastTxCommit(signedEnvelope:string,network:string):Promise<SettlementResult>{try{const raw=decodeSignedTransaction(signedEnvelope).envelope.encodedTransaction,result=await this.rpc<{hash?:string;check_tx?:{code?:number;log?:string};deliver_tx?:{code?:number;log?:string}}>("broadcast_tx_commit",{tx:raw});const code=result.check_tx?.code||result.deliver_tx?.code||0;if(code!==0)return {success:false,network,errorReason:result.deliver_tx?.log||result.check_tx?.log||`chain_code_${code}`};return {success:true,network,transaction:result.hash||createHash("sha256").update(Buffer.from(raw,"base64")).digest("hex").toUpperCase()}}catch(e){return {success:false,network,errorReason:e instanceof Error?e.message:"rpc_error"}}}async status(){return this.rpc<{sync_info:{latest_block_height:string;latest_block_hash:string}}>("status",{})}async block(height:number){return this.rpc<{block_id:{hash:string};block:{header:{height:string;last_block_id?:{hash?:string}};data:{txs?:string[]}}}>("block",{height:String(height)})}async blockResults(height:number){return this.rpc<{height:string;txs_results?:Array<{code?:number;log?:string;events?:Array<{type:string;attributes:Array<{key:string;value:string}>}>}>}>("block_results",{height:String(height)})}}
