import { createHash } from "node:crypto";
import { decodeTxMessages } from "@gnolang/gno-js-client";
import { PubKeySecp256k1,Secp256k1PubKeyType,Tx } from "@gnolang/tm2-js-client";
import { gnoAddressFromPubkey } from "./gno.ts";
export type ChainBlock={height:number;hash:string;parentHash:string;txs:string[]};
export type RpcEvent={type:string;typeUrl?:string;pkg_path?:string;attributes:Array<{key:string;value:string}>};
export type TransferEvent={txIndex:number;eventIndex:number;pkgPath?:string;asset:string;from:string;to:string;amount:string};
export type G402PaymentEvent={txIndex:number;eventIndex:number;pkgPath:string;paymentId:string;payer:string;recipient:string;amount:string;resourceHash:string;nonce:string};
export function planReorg(checkpoint:{height:number;hash:string},incoming:ChainBlock,maxDepth=100){if(incoming.height===checkpoint.height+1&&incoming.parentHash===checkpoint.hash)return {reorg:false,rewindTo:checkpoint.height};const rewindTo=Math.max(0,Math.min(checkpoint.height,incoming.height-1)-maxDepth);return {reorg:true,rewindTo}}
function decodeAttr(v:string){try{const decoded=Buffer.from(v,"base64").toString("utf8"),roundtrip=Buffer.from(decoded,"utf8").toString("base64").replace(/=+$/g,"");return roundtrip===v.replace(/=+$/g,"")&&/^[\x20-\x7E]*$/.test(decoded)?decoded:v}catch{return v}}
export function extractTransfers(results:{txs_results?:Array<{code?:number;events?:RpcEvent[]}>}):TransferEvent[]{const out:TransferEvent[]=[];(results.txs_results||[]).forEach((tx,txIndex)=>{if(tx.code&&tx.code!==0)return;(tx.events||[]).forEach((event,eventIndex)=>{const type=decodeAttr(event.type),attrs=Object.fromEntries(event.attributes.map(a=>[decodeAttr(a.key),decodeAttr(a.value)]));if(type.toLowerCase().includes("transfer")&&attrs.to&&attrs.value)out.push({txIndex,eventIndex,pkgPath:event.pkg_path,asset:event.pkg_path||attrs.pkg_path||attrs.denom||"ugnot",from:attrs.from||"",to:attrs.to,amount:attrs.value})})});return out}
export function extractG402Payments(results:{txs_results?:Array<{code?:number;events?:RpcEvent[]}>},expectedContractPath:string):G402PaymentEvent[]{const out:G402PaymentEvent[]=[];if(!expectedContractPath)return out;(results.txs_results||[]).forEach((tx,txIndex)=>{if(tx.code&&tx.code!==0)return;(tx.events||[]).forEach((event,eventIndex)=>{const pkgPath=event.pkg_path||"";if(event.typeUrl!=="/tm.gnoEvent"||decodeAttr(event.type)!=="G402Payment"||pkgPath!==expectedContractPath)return;const attrs=Object.fromEntries(event.attributes.map(a=>[decodeAttr(a.key),decodeAttr(a.value)]));if(attrs.payment_id&&attrs.payer&&attrs.recipient&&attrs.amount&&attrs.resource_hash&&attrs.nonce)out.push({txIndex,eventIndex,pkgPath,paymentId:attrs.payment_id,payer:attrs.payer,recipient:attrs.recipient,amount:attrs.amount,resourceHash:attrs.resource_hash,nonce:attrs.nonce})})});return out}
export function txHash(tx:string){return createHash("sha256").update(Buffer.from(tx,"base64")).digest("hex").toUpperCase()}

export type DecodedChainTransaction={memo:string;signer:string;recipient:string;asset:string;amount:string;kind:"native"|"grc20"|"realm"|"unsupported";paymentId?:string;nonce?:string;resourceHash?:string;contractPath?:string};
export function decodeChainTransaction(encoded:string):DecodedChainTransaction{try{const tx=Tx.decode(Buffer.from(encoded,"base64")),message=(decodeTxMessages(tx.messages) as Array<Record<string,unknown>>)[0]||{},type=String(message["@type"]||"");let signer="";const signature=tx.signatures[0];if(signature?.pub_key?.type_url===Secp256k1PubKeyType)signer=gnoAddressFromPubkey(Buffer.from(PubKeySecp256k1.decode(signature.pub_key.value).key));let recipient="",asset="",amount="",kind:DecodedChainTransaction["kind"]="unsupported",contractPath:string|undefined;if(type==="/bank.MsgSend"){kind="native";signer=String(message.from_address||signer);recipient=String(message.to_address||"");const value=String(message.amount||"");const match=value.match(/^(\d+)([A-Za-z][A-Za-z0-9/_-]*)$/);amount=match?.[1]||value;asset=match?.[2]||""}else if(type==="/vm.m_call"){const args=Array.isArray(message.args)?message.args:[];signer=String(message.caller||signer);contractPath=String(message.pkg_path||"");const func=String(message.func||"");if(func==="Transfer"){kind="grc20";recipient=String(args[0]||"");amount=String(args[1]||"");asset=contractPath}else if(func==="Pay"){kind="realm";recipient=String(args[1]||"");amount=String(args[2]||"");asset=String(message.send||"").replace(/^\d+/,"");contractPath=String(message.pkg_path||"")}}const memo=tx.memo||"",binding=memo.match(/^g402:([A-Za-z0-9_-]{16,128}):([A-Za-z0-9_-]{16,128}):([a-f0-9]{64})$/);return {memo,signer,recipient,asset,amount,kind,paymentId:binding?.[1],nonce:binding?.[2],resourceHash:binding?.[3],contractPath}}catch{return {memo:"",signer:"",recipient:"",asset:"",amount:"",kind:"unsupported"}}}
