import { createHash } from "node:crypto";
export type ChainBlock={height:number;hash:string;parentHash:string;txs:string[]};
export type TransferEvent={txIndex:number,eventIndex:number;asset:string;from:string;to:string;amount:string};
export type G402PaymentEvent={txIndex:number;eventIndex:number;paymentId:string;payer:string;recipient:string;amount:string;resourceHash:string;nonce:string};
export function planReorg(checkpoint:{height:number;hash:string},incoming:ChainBlock,maxDepth=100){if(incoming.height===checkpoint.height+1&&incoming.parentHash===checkpoint.hash)return {reorg:false,rewindTo:checkpoint.height};const rewindTo=Math.max(0,Math.min(checkpoint.height,incoming.height-1)-maxDepth);return {reorg:true,rewindTo}}
function decodeAttr(v:string){try{const decoded=Buffer.from(v,"base64").toString("utf8"),roundtrip=Buffer.from(decoded,"utf8").toString("base64").replace(/=+$/g,"");return roundtrip===v.replace(/=+$/g,"")&&/^[\x20-\x7E]*$/.test(decoded)?decoded:v}catch{return v}}
export function extractTransfers(results:{txs_results?:Array<{code?:number;events?:Array<{type:string;attributes:Array<{key:string;value:string}>}>}>}):TransferEvent[]{const out:TransferEvent[]=[];(results.txs_results||[]).forEach((tx,txIndex)=>{if(tx.code&&tx.code!==0)return;(tx.events||[]).forEach((event,eventIndex)=>{const type=decodeAttr(event.type),attrs=Object.fromEntries(event.attributes.map(a=>[decodeAttr(a.key),decodeAttr(a.value)]));if(type.toLowerCase().includes("transfer")&&attrs.to&&attrs.value)out.push({txIndex,eventIndex,asset:attrs.pkg_path||attrs.denom||"ugnot",from:attrs.from||"",to:attrs.to,amount:attrs.value})})});return out}
export function extractG402Payments(results:{txs_results?:Array<{code?:number;events?:Array<{type:string;attributes:Array<{key:string;value:string}>}>}>}):G402PaymentEvent[]{const out:G402PaymentEvent[]=[];(results.txs_results||[]).forEach((tx,txIndex)=>{if(tx.code&&tx.code!==0)return;(tx.events||[]).forEach((event,eventIndex)=>{if(decodeAttr(event.type)!=="G402Payment")return;const attrs=Object.fromEntries(event.attributes.map(a=>[decodeAttr(a.key),decodeAttr(a.value)]));if(attrs.payment_id&&attrs.payer&&attrs.recipient&&attrs.amount&&attrs.resource_hash&&attrs.nonce)out.push({txIndex,eventIndex,paymentId:attrs.payment_id,payer:attrs.payer,recipient:attrs.recipient,amount:attrs.amount,resourceHash:attrs.resource_hash,nonce:attrs.nonce})})});return out}
export function txHash(tx:string){return createHash("sha256").update(Buffer.from(tx,"base64")).digest("hex").toUpperCase()}
