import { neon } from "@neondatabase/serverless";
import type { AgentPolicy } from "./policy.ts";

export type PaymentStatus="verifying"|"verified"|"approval_required"|"settling"|"broadcast"|"settled"|"failed"|"reverted";
export type PaymentRecord={id:string;paymentId:string;fingerprint?:string;nonce?:string;txHash:string|null;network:string;payer:string;payTo:string;asset:string;amount:string;status:PaymentStatus;error:string|null;merchantId?:string;agentId?:string;policyId?:string;serviceQuoteId?:string;createdAt:string};
const memory=new Map<string,PaymentRecord>();
const usedNonces=new Set<string>();
const memoryPolicies=new Map<string,AgentPolicy>();
const memoryApprovals=new Map<string,"approved"|"rejected">();
export type AgentRecord={id:string;name:string;walletAddress:string;status:"active"|"suspended";createdAt:string};
const memoryAgents=new Map<string,AgentRecord>();
export async function findPayment(paymentId:string):Promise<PaymentRecord|null>{
  if(!process.env.DATABASE_URL)return memory.get(paymentId)||null;
  const sql=neon(process.env.DATABASE_URL); const rows=await sql`select * from payments where payment_id=${paymentId} limit 1`;
  if(!rows[0])return null; const r=rows[0]; return {id:r.id,paymentId:r.payment_id,fingerprint:r.fingerprint||undefined,nonce:r.nonce||undefined,txHash:r.tx_hash,network:r.network,payer:r.payer,payTo:r.pay_to,asset:r.asset,amount:String(r.amount),status:r.status,error:r.error,merchantId:r.merchant_id||undefined,agentId:r.agent_id||undefined,policyId:r.policy_id||undefined,serviceQuoteId:r.service_quote_id||undefined,createdAt:new Date(r.created_at).toISOString()};
}
export async function savePayment(record:PaymentRecord):Promise<void>{
  if(!process.env.DATABASE_URL){memory.set(record.paymentId,record);return;}
  const sql=neon(process.env.DATABASE_URL); await sql`insert into payments(id,payment_id,fingerprint,nonce,tx_hash,network,payer,pay_to,asset,amount,status,error,merchant_id,agent_id,policy_id,service_quote_id,created_at) values(${record.id},${record.paymentId},${record.fingerprint||null},${record.nonce||null},${record.txHash},${record.network},${record.payer},${record.payTo},${record.asset},${record.amount},${record.status},${record.error},${record.merchantId||null},${record.agentId||null},${record.policyId||null},${record.serviceQuoteId||null},${record.createdAt}) on conflict(payment_id) do update set tx_hash=excluded.tx_hash,status=excluded.status,error=excluded.error,updated_at=now()`;
}

export async function claimSettlement(record:PaymentRecord):Promise<{claimed:boolean;existing:PaymentRecord|null}>{
  if(!process.env.DATABASE_URL){const existing=memory.get(record.paymentId)||null;if(existing){if(existing.fingerprint!==record.fingerprint)throw new Error("idempotency_conflict");return {claimed:false,existing}}const nonceKey=`${record.network}:${record.payer}:${record.nonce}`;if(usedNonces.has(nonceKey))throw new Error("nonce_reused");usedNonces.add(nonceKey);memory.set(record.paymentId,record);return {claimed:true,existing:null}}
  const sql=neon(process.env.DATABASE_URL);const rows=await sql`insert into payments(id,payment_id,fingerprint,nonce,tx_hash,network,payer,pay_to,asset,amount,status,error,merchant_id,agent_id,policy_id,service_quote_id,created_at) values(${record.id},${record.paymentId},${record.fingerprint},${record.nonce},null,${record.network},${record.payer},${record.payTo},${record.asset},${record.amount},${record.status},null,${record.merchantId||null},${record.agentId||null},${record.policyId||null},${record.serviceQuoteId||null},${record.createdAt}) on conflict do nothing returning payment_id`;
  if(rows.length)return {claimed:true,existing:null};const existing=await findPayment(record.paymentId);if(existing&&existing.fingerprint!==record.fingerprint)throw new Error("idempotency_conflict");if(!existing)throw new Error("nonce_reused");return {claimed:false,existing};
}
export async function resumeApprovedSettlement(paymentId:string,fingerprint:string):Promise<boolean>{if(!process.env.DATABASE_URL){const record=memory.get(paymentId);if(!record||record.fingerprint!==fingerprint||record.status!=="approval_required")return false;memory.set(paymentId,{...record,status:"settling"});return true}const sql=neon(process.env.DATABASE_URL);const rows=await sql`update payments set status='settling',updated_at=now() where payment_id=${paymentId} and fingerprint=${fingerprint} and status='approval_required' returning payment_id`;return rows.length===1}
export async function getPolicyUsage(agentId:string,now=new Date()):Promise<{daily:string;monthly:string}>{
  if(!process.env.DATABASE_URL){let daily=0n,monthly=0n;for(const p of memory.values())if(p.status==="settled"){const d=new Date(p.createdAt);if(d.getUTCFullYear()===now.getUTCFullYear()&&d.getUTCMonth()===now.getUTCMonth()){monthly+=BigInt(p.amount);if(d.getUTCDate()===now.getUTCDate())daily+=BigInt(p.amount)}}return {daily:String(daily),monthly:String(monthly)}}
  const sql=neon(process.env.DATABASE_URL);const rows=await sql`select coalesce(sum(amount) filter(where created_at>=date_trunc('day',now())),0)::text daily,coalesce(sum(amount) filter(where created_at>=date_trunc('month',now())),0)::text monthly from payments where agent_id=${agentId} and status='settled'`;return {daily:String(rows[0]?.daily||"0"),monthly:String(rows[0]?.monthly||"0")}
}
export async function appendAudit(actor:string,action:string,target:string,metadata:Record<string,unknown>={}){if(!process.env.DATABASE_URL)return;const sql=neon(process.env.DATABASE_URL);await sql`insert into audit_log(id,actor,action,target,metadata) values(${crypto.randomUUID()},${actor},${action},${target},${JSON.stringify(metadata)}::jsonb)`}
export async function getAgentPolicy(agentId:string):Promise<AgentPolicy|null>{if(!process.env.DATABASE_URL)return [...memoryPolicies.values()].find(p=>p.agentId===agentId&&p.enabled)||null;const sql=neon(process.env.DATABASE_URL);const rows=await sql`select * from agent_policies where agent_id=${agentId} and enabled=true order by created_at desc limit 1`;if(!rows[0])return null;const r=rows[0];return {id:r.id,agentId:r.agent_id,enabled:r.enabled,network:r.network,allowedMerchants:r.allowed_merchants||[],allowedRecipients:r.allowed_recipients||[],allowedAssets:r.allowed_assets||[],maxPerPayment:String(r.max_per_payment),dailyBudget:String(r.daily_budget),monthlyBudget:String(r.monthly_budget),approvalThreshold:String(r.approval_threshold),validFrom:new Date(r.valid_from).toISOString(),validUntil:new Date(r.valid_until).toISOString(),requireResourceBinding:r.require_resource_binding}}
export async function hasApproval(paymentId:string):Promise<boolean>{if(!process.env.DATABASE_URL)return [...memoryApprovals.entries()].some(([key,value])=>key.startsWith(`${paymentId}:`)&&value==="approved");const sql=neon(process.env.DATABASE_URL);const rows=await sql`select 1 from payment_approvals where payment_id=${paymentId} and decision='approved' limit 1`;return rows.length>0}
export async function listPayments(limit=100):Promise<PaymentRecord[]>{if(!process.env.DATABASE_URL)return [...memory.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,limit);const sql=neon(process.env.DATABASE_URL);const rows=await sql`select * from payments order by created_at desc limit ${Math.min(Math.max(limit,1),500)}`;return rows.map(r=>({id:r.id,paymentId:r.payment_id,fingerprint:r.fingerprint||undefined,nonce:r.nonce||undefined,txHash:r.tx_hash,network:r.network,payer:r.payer,payTo:r.pay_to,asset:r.asset,amount:String(r.amount),status:r.status,error:r.error,merchantId:r.merchant_id||undefined,agentId:r.agent_id||undefined,policyId:r.policy_id||undefined,serviceQuoteId:r.service_quote_id||undefined,createdAt:new Date(r.created_at).toISOString()}))}
export async function upsertAgentPolicy(policy:AgentPolicy){if(!process.env.DATABASE_URL){memoryPolicies.set(policy.id,policy);return}const sql=neon(process.env.DATABASE_URL);await sql`insert into agent_policies(id,agent_id,enabled,network,allowed_merchants,allowed_recipients,allowed_assets,max_per_payment,daily_budget,monthly_budget,approval_threshold,valid_from,valid_until,require_resource_binding) values(${policy.id},${policy.agentId},${policy.enabled},${policy.network},${policy.allowedMerchants},${policy.allowedRecipients},${policy.allowedAssets},${policy.maxPerPayment},${policy.dailyBudget},${policy.monthlyBudget},${policy.approvalThreshold},${policy.validFrom},${policy.validUntil},${policy.requireResourceBinding}) on conflict(id) do update set enabled=excluded.enabled,network=excluded.network,allowed_merchants=excluded.allowed_merchants,allowed_recipients=excluded.allowed_recipients,allowed_assets=excluded.allowed_assets,max_per_payment=excluded.max_per_payment,daily_budget=excluded.daily_budget,monthly_budget=excluded.monthly_budget,approval_threshold=excluded.approval_threshold,valid_from=excluded.valid_from,valid_until=excluded.valid_until,require_resource_binding=excluded.require_resource_binding,updated_at=now()`}
export async function recordApproval(paymentId:string,approver:string,decision:"approved"|"rejected",reason?:string){if(!process.env.DATABASE_URL){memoryApprovals.set(`${paymentId}:${approver}`,decision);return}const sql=neon(process.env.DATABASE_URL);await sql`insert into payment_approvals(id,payment_id,approver,decision,reason) values(${crypto.randomUUID()},${paymentId},${approver},${decision},${reason||null}) on conflict(payment_id,approver) do update set decision=excluded.decision,reason=excluded.reason,created_at=now()`}
export async function upsertAgent(agent:AgentRecord){if(!process.env.DATABASE_URL){memoryAgents.set(agent.id,agent);return}const sql=neon(process.env.DATABASE_URL);await sql`insert into agents(id,name,wallet_address,status,created_at) values(${agent.id},${agent.name},${agent.walletAddress},${agent.status},${agent.createdAt}) on conflict(id) do update set name=excluded.name,wallet_address=excluded.wallet_address,status=excluded.status,updated_at=now()`}
export async function listAgents(limit=100):Promise<AgentRecord[]>{if(!process.env.DATABASE_URL)return [...memoryAgents.values()].slice(0,limit);const sql=neon(process.env.DATABASE_URL);const rows=await sql`select id,name,wallet_address,status,created_at from agents order by created_at desc limit ${Math.min(Math.max(limit,1),500)}`;return rows.map(r=>({id:r.id,name:r.name,walletAddress:r.wallet_address,status:r.status,createdAt:new Date(r.created_at).toISOString()}))}
