import {createHash} from "node:crypto";
export type ServiceBudget={agentId:string;service:string;perRequest:string;daily:string;monthly:string};
export type ServiceUsage={daily:string;monthly:string};
export function canonicalHash(value:unknown){const sort=(v:unknown):unknown=>Array.isArray(v)?v.map(sort):v&&typeof v==="object"?Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,sort(x)])):v;return createHash("sha256").update(JSON.stringify(sort(value))).digest("hex")}
export function evaluateServiceBudget(budget:ServiceBudget,amount:string,usage:ServiceUsage){const value=BigInt(amount);if(value>BigInt(budget.perRequest))return {allowed:false,reason:"service_per_request_limit"};if(value+BigInt(usage.daily)>BigInt(budget.daily))return {allowed:false,reason:"service_daily_budget"};if(value+BigInt(usage.monthly)>BigInt(budget.monthly))return {allowed:false,reason:"service_monthly_budget"};return {allowed:true}}
export function ceilDiv(value:bigint,divisor:bigint){if(divisor<=0n)throw new Error("invalid_divisor");return (value+divisor-1n)/divisor}
export type ExpectedSettlement={quoteId:string;network:string;asset:string;amount:string;payTo:string;agentId?:string;minConfirmations?:number};
export interface SettlementAdapter{verify(paymentId:string,expected:ExpectedSettlement):Promise<{valid:boolean;reason?:string;transaction?:string}>}
export class CircuitBreaker{private failures=new Map<string,{count:number;openUntil:number}>();constructor(private threshold=3,private coolDownMs=30_000){}available(id:string,now=Date.now()){return (this.failures.get(id)?.openUntil||0)<=now}success(id:string){this.failures.delete(id)}failure(id:string,now=Date.now()){const state=this.failures.get(id)||{count:0,openUntil:0};state.count++;if(state.count>=this.threshold)state.openUntil=now+this.coolDownMs;this.failures.set(id,state)}snapshot(){return Object.fromEntries(this.failures)}}
