export {};
const base=(process.env.STAGING_BASE_URL||"").replace(/\/$/,"");
if(!base)throw new Error("STAGING_BASE_URL is required");
const auth:Record<string,string>={};if(process.env.STAGING_FACILITATOR_KEY)auth.authorization=`Bearer ${process.env.STAGING_FACILITATOR_KEY}`;
const health=await fetch(`${base}/api/health`,{headers:auth}),healthBody=await health.json() as {status?:string;locks?:{gnoMainnet?:boolean};network?:string};
if(!health.ok||healthBody.locks?.gnoMainnet!==true||healthBody.network!=="gno:pearl-1")throw new Error(`unsafe_health:${JSON.stringify(healthBody)}`);
const selfTestAddress=`g1${"q".repeat(38)}`,challenge=await fetch(`${base}/api/demo/paid-data?payTo=${selfTestAddress}`),challengeBody=await challenge.json() as {paymentRequirements?:{network?:string;extra?:{nonce?:string}}};
if(challenge.status!==402||challengeBody.paymentRequirements?.network!=="gno:pearl-1"||!challenge.headers.get("payment-required"))throw new Error("invalid_402_challenge");
if(!challengeBody.paymentRequirements.extra?.nonce)throw new Error("challenge_nonce_missing");
console.log(JSON.stringify({ok:true,checks:["health","mainnet_lock","x402_challenge","nonce"],base}));
