import {getPostgres} from "../../../db/postgres.ts";
export type StoredObject={id:string;cid:string;sha256:string;sizeBytes:number;filename?:string;contentType?:string;tags:string[];ownerAgentId?:string;retentionDays:number;replicas:number;status:string;ipfsProvider?:string;datasetId?:string;pieceCid?:string;railId?:string;proofStatus?:string;expiresAt:string;createdAt:string};
const objects=new Map<string,StoredObject>(),content=new Map<string,Uint8Array>();
export async function saveObject(object:StoredObject,bytes?:Uint8Array){if(!process.env.DATABASE_URL){objects.set(object.cid,object);if(bytes)content.set(object.cid,bytes);return}const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into storage_objects(id,cid,sha256,size_bytes,filename,content_type,tags,owner_agent_id,retention_days,replicas,status,ipfs_provider,dataset_id,piece_cid,payment_rail_id,proof_status,expires_at,created_at) values(${object.id},${object.cid},${object.sha256},${object.sizeBytes},${object.filename||null},${object.contentType||null},${object.tags},${object.ownerAgentId||null},${object.retentionDays},${object.replicas},${object.status},${object.ipfsProvider||null},${object.datasetId||null},${object.pieceCid||null},${object.railId||null},${object.proofStatus||null},${object.expiresAt},${object.createdAt}) on conflict(cid) do update set status=excluded.status,dataset_id=excluded.dataset_id,piece_cid=excluded.piece_cid,payment_rail_id=excluded.payment_rail_id,proof_status=excluded.proof_status,updated_at=now()`}
export async function getObject(cid:string):Promise<StoredObject|null>{if(!process.env.DATABASE_URL)return objects.get(cid)||null;const sql=getPostgres(process.env.DATABASE_URL),rows=await sql`select * from storage_objects where cid=${cid}`;if(!rows[0])return null;const r=rows[0];return {id:r.id,cid:r.cid,sha256:r.sha256,sizeBytes:Number(r.size_bytes),filename:r.filename||undefined,contentType:r.content_type||undefined,tags:r.tags||[],ownerAgentId:r.owner_agent_id||undefined,retentionDays:r.retention_days,replicas:r.replicas,status:r.status,ipfsProvider:r.ipfs_provider||undefined,datasetId:r.dataset_id||undefined,pieceCid:r.piece_cid||undefined,railId:r.payment_rail_id||undefined,proofStatus:r.proof_status||undefined,expiresAt:new Date(r.expires_at).toISOString(),createdAt:new Date(r.created_at).toISOString()}}
export function getMockContent(cid:string){return content.get(cid)}
export async function searchObjects(query:string,tags:string[],limit:number,agentId?:string){if(!process.env.DATABASE_URL)return [...objects.values()].filter(x=>(!agentId||x.ownerAgentId===agentId)&&(!query||x.filename?.toLowerCase().includes(query.toLowerCase())||x.cid.includes(query))&&tags.every(t=>x.tags.includes(t))).slice(0,limit);const sql=getPostgres(process.env.DATABASE_URL),pattern=`%${query.replace(/[%_]/g,"\\$&")}%`,rows=await sql`select * from storage_objects where (${agentId||null}::uuid is null or owner_agent_id=${agentId||null}) and (${query}='' or filename ilike ${pattern} escape '\\' or cid like ${pattern} escape '\\') and (${tags}::text[] <@ tags) order by created_at desc limit ${limit}`;return Promise.all(rows.map(r=>getObject(String(r.cid))))}
export async function saveReceipt(input:{objectId:string;quoteId:string;kind:string;provider?:string;externalId?:string;status:string;txHash?:string;metadata?:Record<string,unknown>}){if(!process.env.DATABASE_URL)return;const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into storage_receipts(id,object_id,quote_id,kind,provider,external_id,status,tx_hash,metadata) values(${crypto.randomUUID()},${input.objectId},${input.quoteId},${input.kind},${input.provider||null},${input.externalId||null},${input.status},${input.txHash||null},${JSON.stringify(input.metadata||{})}::jsonb)`}
export async function saveRetrievalReceipt(input:{cid:string;quoteId:string;agentId?:string;bytes:number;provider?:string;channel?:string;voucherNonce?:number;requestId:string}){if(!process.env.DATABASE_URL)return;const sql=getPostgres(process.env.DATABASE_URL);await sql`insert into retrieval_receipts(id,cid,quote_id,agent_id,bytes_sent,provider,payment_channel,voucher_nonce,request_id) values(${crypto.randomUUID()},${input.cid},${input.quoteId},${input.agentId||null},${input.bytes},${input.provider||null},${input.channel||null},${input.voucherNonce||null},${input.requestId}) on conflict(request_id) do nothing`}
