import { neon } from "@neondatabase/serverless";
import { GnoRpcClient } from "../lib/gno.ts";
import { extractG402Payments,extractTransfers,planReorg,txHash } from "../lib/indexer.ts";
import { alertOps,metrics } from "../lib/observability.ts";
const interval=Number(process.env.INDEXER_INTERVAL_MS||4000),network=process.env.GNO_NETWORK_ID||"gno:staging",maxReorg=Number(process.env.INDEXER_MAX_REORG_DEPTH||100),confirmations=Number(process.env.INDEXER_CONFIRMATIONS||2),databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl)throw new Error("DATABASE_URL is required for production indexer");
const sql=neon(databaseUrl),rpc=new GnoRpcClient();
const workerId=crypto.randomUUID(),leaseName=`g402-indexer:${network}`;
async function acquireLease(){const rows=await sql`insert into worker_leases(name,owner_id,expires_at) values(${leaseName},${workerId},now()+interval '30 seconds') on conflict(name) do update set owner_id=excluded.owner_id,expires_at=excluded.expires_at,heartbeat_at=now() where worker_leases.expires_at<now() or worker_leases.owner_id=${workerId} returning owner_id`;return rows.length===1&&String(rows[0].owner_id)===workerId}
async function checkpoint(){const rows=await sql`select height,block_hash from indexer_checkpoints where network=${network}`;return rows[0]?{height:Number(rows[0].height),hash:String(rows[0].block_hash)}:{height:0,hash:""}}
async function rewind(height:number){await sql`update indexed_blocks set canonical=false where network=${network} and height>${height}`;await sql`update payments set status='reverted',confirmations=0 where network=${network} and block_height>${height} and status='settled'`;const rows=await sql`select block_hash,parent_hash from indexed_blocks where network=${network} and height=${height} and canonical=true`;await sql`insert into indexer_checkpoints(network,height,block_hash,parent_hash) values(${network},${height},${String(rows[0]?.block_hash||"")},${String(rows[0]?.parent_hash||"")}) on conflict(network) do update set height=excluded.height,block_hash=excluded.block_hash,parent_hash=excluded.parent_hash,updated_at=now()`}
async function indexHeight(height:number){const [block,results]=await Promise.all([rpc.block(height),rpc.blockResults(height)]),hash=block.block_id.hash,parentHash=block.block.header.last_block_id?.hash||"",cp=await checkpoint(),plan=planReorg(cp,{height,hash,parentHash,txs:block.block.data.txs||[]},maxReorg);if(plan.reorg&&cp.height>0){await rewind(plan.rewindTo);metrics.inc("g402_reorgs",{network});await alertOps("g402 chain reorg detected",{network,checkpoint:cp,height,parentHash,rewindTo:plan.rewindTo});return false}await sql`insert into indexed_blocks(network,height,block_hash,parent_hash,canonical) values(${network},${height},${hash},${parentHash},true) on conflict(network,height) do update set block_hash=excluded.block_hash,parent_hash=excluded.parent_hash,canonical=true,indexed_at=now()`;const txs=block.block.data.txs||[],events=extractTransfers(results),contractEvents=extractG402Payments(results);for(const event of events){const hashValue=txs[event.txIndex]?txHash(txs[event.txIndex]):null;if(hashValue)await sql`update payments set tx_hash=coalesce(tx_hash,${hashValue}),block_height=${height},block_hash=${hash},status='settled',confirmations=1,updated_at=now() where network=${network} and tx_hash=${hashValue}`}for(const event of contractEvents){const hashValue=txs[event.txIndex]?txHash(txs[event.txIndex]):null;if(hashValue)await sql`update payments set tx_hash=coalesce(tx_hash,${hashValue}),block_height=${height},block_hash=${hash},status='settled',confirmations=1,updated_at=now() where network=${network} and payment_id=${event.paymentId} and payer=${event.payer} and pay_to=${event.recipient} and amount=${event.amount} and nonce=${event.nonce}`}await sql`insert into indexer_checkpoints(network,height,block_hash,parent_hash) values(${network},${height},${hash},${parentHash}) on conflict(network) do update set height=excluded.height,block_hash=excluded.block_hash,parent_hash=excluded.parent_hash,updated_at=now()`;await sql`update payments set confirmations=least(${confirmations},${height}-block_height+1) where network=${network} and status='settled' and block_height is not null`;metrics.inc("g402_blocks_indexed",{network});return true}
async function tick(){const latest=Number((await rpc.status()).sync_info.latest_block_height);let cp=await checkpoint();for(let height=cp.height+1;height<=latest-confirmations+1;height++){const ok=await indexHeight(height);if(!ok){cp=await checkpoint();height=cp.height}}}
async function processReindexJob(){const rows=await sql`with candidate as (select id from indexer_jobs where network=${network} and status='queued' order by created_at for update skip locked limit 1) update indexer_jobs j set status='running',attempts=attempts+1,updated_at=now() from candidate c where j.id=c.id returning j.id,j.from_height`;if(!rows[0])return;const id=String(rows[0].id);try{await rewind(Math.max(0,Number(rows[0].from_height)-1));await tick();await sql`update indexer_jobs set status='complete',updated_at=now(),last_error=null where id=${id}`}catch(e){await sql`update indexer_jobs set status='failed',updated_at=now(),last_error=${e instanceof Error?e.message:String(e)} where id=${id}`;throw e}}
async function loop(){for(;;){try{if(await acquireLease()){await processReindexJob();await tick()}}catch(e){const message=e instanceof Error?e.message:String(e);console.error(JSON.stringify({level:"error",event:"index_failed",message}));void alertOps("g402 indexer failed",{network,message})}await new Promise(r=>setTimeout(r,interval))}}
void loop();
