"use client";
import { useState } from "react";
import type { ScanBlock,ScanStatus,ScanTransaction } from "@/lib/scan";

type ScanPayload={status:ScanStatus;blocks:ScanBlock[];transactions:ScanTransaction[]};
function short(value:string|null,front=9,back=6){if(!value)return "—";return value.length>front+back+1?`${value.slice(0,front)}…${value.slice(-back)}`:value}
function time(value:string|null){if(!value)return "—";return new Date(value).toLocaleString("ko-KR")}

export default function ScanClient({initial}:{initial:ScanPayload}){const [data,setData]=useState(initial),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function load(q=query){const response=await fetch(`/api/v1/scan?q=${encodeURIComponent(q)}`,{cache:"no-store"}),body=await response.json() as ScanPayload&{error?:string};if(!response.ok)throw new Error(body.error||"scan_load_failed");setData(body)}async function search(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{await load()}catch(reason){setError(reason instanceof Error?reason.message:"scan_load_failed")}finally{setBusy(false)}}async function sync(){setBusy(true);setError("");try{const response=await fetch("/api/internal/index",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({maxBlocks:20})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"index_failed");await load()}catch(reason){setError(reason instanceof Error?reason.message:"index_failed")}finally{setBusy(false)}}const status=data.status;return <>
  <section className="scanToolbar card"><form onSubmit={search} className="scanSearch"><input aria-label="Search chain" value={query} onChange={event=>setQuery(event.target.value)} placeholder="TX hash, payment ID, address or block height"/><button className="button" disabled={busy}>{busy?"Working…":"Search"}</button></form><button className="button secondary" onClick={sync} disabled={busy}>Sync latest blocks</button></section>
  {error&&<div className="errorBanner" role="alert">{error}</div>}
  <section className="grid stats"><div className="card stat"><label>CHAIN HEIGHT</label><strong>{status.chainHeight||"—"}</strong></div><div className="card stat"><label>INDEXED HEIGHT</label><strong>{status.indexedHeight||"—"}</strong></div><div className="card stat"><label>INDEX LAG</label><strong className={status.lag>5?"pending":"success"}>{status.lag}</strong><small>blocks</small></div><div className="card stat"><label>G402 PAYMENTS</label><strong>{status.settledPayments}</strong><small>settled</small></div></section>
  <section className="grid scanLayout"><div className="card"><div className="sectionTitle"><div><div className="eyebrow">Canonical chain</div><h2>Transactions</h2></div><span className="mutedText">{data.transactions.length} results</span></div><div className="tableWrap"><table className="table"><thead><tr><th>Hash</th><th>Block</th><th>Time</th><th>Route</th><th>Amount</th><th>Result</th></tr></thead><tbody>{data.transactions.length?data.transactions.map(tx=><tr key={tx.txHash}><td><details><summary className="mono scanLink">{short(tx.txHash)}</summary><div className="txDetail"><p><b>Transaction</b><span className="mono">{tx.txHash}</span></p><p><b>Memo</b><span className="mono">{tx.memo||"—"}</span></p><p><b>Payment ID</b><span className="mono">{tx.paymentId||"—"}</span></p><p><b>Block hash</b><span className="mono">{tx.blockHash}</span></p>{tx.log&&<p><b>Log</b><span>{tx.log}</span></p>}</div></details></td><td>#{tx.height}</td><td>{time(tx.blockTime)}</td><td className="mono">{short(tx.signer)} → {short(tx.recipient)}</td><td>{tx.amount||"—"} <span className="mutedText">{short(tx.asset,6,4)}</span></td><td><span className={(tx.code===0?"success":"failed")+" badge"}>{tx.code===0?"success":"failed"}</span></td></tr>):<tr><td colSpan={6}>No indexed transactions. Select “Sync latest blocks”.</td></tr>}</tbody></table></div></div>
    <aside className="card"><div className="sectionTitle"><div><div className="eyebrow">Recent</div><h2>Blocks</h2></div></div><div className="blockList">{data.blocks.length?data.blocks.map(block=><div className="blockRow" key={`${block.height}:${block.blockHash}`}><div><b>#{block.height}</b><span className="mono">{short(block.blockHash,8,5)}</span></div><div><span>{block.txCount} tx</span><time>{time(block.blockTime)}</time></div></div>):<p className="mutedText">No blocks indexed yet.</p>}</div><div className="indexMeta"><span>Network</span><b>{status.network}</b><span>Chain ID</span><b>{status.chainId}</b><span>Last sync</span><b>{time(status.updatedAt)}</b></div></aside></section>
  </>}
